// Generated from the APTICON 2026 brochure (brochure-scripts/generate.py). Edit names/roles here directly if needed.
import type { CommitteeGroup, CommitteeMember } from "@/lib/committee-data";

export const CHIEF_GUESTS: CommitteeMember[] = [
  { name: "Shri Ramen Deka", role: "Chief Guest", designation: "Hon'ble Governor of Chhattisgarh", image: "/committee/brochure/chief-guests/ramen-deka.jpg" },
  { name: "Shri Vishnu Deo Sai", role: "Chief Guest (Prize Distribution Ceremony)", designation: "Hon'ble Chief Minister of Chhattisgarh", image: "/committee/brochure/chief-guests/vishnu-deo-sai.jpg" },
];

export const PATRONS: CommitteeMember[] = [
  { name: "Prof. Sachchidanand Shukla", role: "Patron", designation: "Vice Chancellor", institution: "Pt. Ravishankar Shukla University", image: "/committee/brochure/patrons/sachchidanand-shukla.jpg" },
  { name: "Dr. Montu Kumar M. Patel", role: "Patron", designation: "President", institution: "Pharmacy Council of India", image: "/committee/brochure/patrons/montu-kumar-m-patel.jpg" },
  { name: "Prof. B. Suresh", role: "Patron", designation: "Pro Chancellor", institution: "JSS AHER", image: "/committee/brochure/patrons/b-suresh.jpg" },
  { name: "Prof. Atul Kumar Nasa", role: "Patron", designation: "President", institution: "IPGA", image: "/committee/brochure/patrons/atul-kumar-nasa.jpg" },
  { name: "Dr. T. V. Narayana", role: "Patron", designation: "Gen. Secretary", institution: "IPCA", image: "/committee/brochure/patrons/t-v-narayana.jpg" },
  { name: "Dr. R. N. Gupta", role: "Patron", designation: "President", institution: "IPA", image: "/committee/brochure/patrons/r-n-gupta.jpg" },
  { name: "Dr. Milind J. Umekar", role: "Patron", designation: "President", institution: "APTI", image: "/committee/brochure/patrons/milind-j-umekar.jpg" },
];

export const CO_PATRONS: CommitteeMember[] = [
  { name: "Mr. Santosh Rungta", role: "Co-Patron", designation: "Chancellor", institution: "Rungta International Skills University, Bhilai", image: "/committee/brochure/co-patrons/santosh-rungta.jpg" },
  { name: "Mr. Kishore Jadwani", role: "Co-Patron", designation: "Chancellor", institution: "Columbia Professional University, Raipur", image: "/committee/brochure/co-patrons/kishore-jadwani.jpg" },
  { name: "Mr. Prashant Jain", role: "Co-Patron", designation: "Pro-Chancellor", institution: "SAGE University, Bhopal & Indore", image: "/committee/brochure/co-patrons/prashant-jain.jpg" },
  { name: "Mr. I. P. Mishra", role: "Co-Patron", designation: "Chancellor", institution: "Shri Shankaracharya Professional University, Bhilai", image: "/committee/brochure/co-patrons/i-p-mishra.jpg" },
  { name: "Dr. Balvir S. Tomar", role: "Co-Patron", designation: "Founder & Chancellor", institution: "NIMS, Jaipur", image: "/committee/brochure/co-patrons/balvir-s-tomar.jpg" },
  { name: "Dr. Vijay D. Patil", role: "Co-Patron", designation: "Chancellor", institution: "D. Y. Patil University, Navi Mumbai", image: "/committee/brochure/co-patrons/vijay-d-patil.jpg" },
  { name: "Dr. Manju Singh", role: "Co-Patron", designation: "Director, University Institute of Pharmacy", institution: "Pt. Ravishankar Shukla University, Raipur", image: "/committee/brochure/co-patrons/manju-singh.jpg" },
  { name: "Dr. Sanjay Jain", role: "Co-Patron", designation: "President", institution: "MP State Pharmacy Council, Bhopal", image: "/committee/brochure/co-patrons/sanjay-jain.jpg" },
  { name: "Mr. Kinshuk Trivedi", role: "Co-Patron", designation: "Vice President", institution: "Sri Aurobindo Institute of Pharmacy, Indore", image: "/committee/brochure/co-patrons/kinshuk-trivedi.jpg" },
  { name: "Dr. Arun S. Bhatnagar", role: "Co-Patron", designation: "Director General", institution: "Indore Institute of Pharmacy, IIST, IIM&R, Indore", image: "/committee/brochure/co-patrons/arun-s-bhatnagar.jpg" },
  { name: "Dr. Ashutosh Shukla", role: "Co-Patron", designation: "Chairman", institution: "Gracious College of Pharmacy, Raipur", image: "/committee/brochure/co-patrons/ashutosh-shukla.jpg" },
  { name: "Dr. Anil Kharia", role: "Co-Patron", designation: "Chairman", institution: "Modern Group of Institutions and Industries, Indore (MP)", image: "/committee/brochure/co-patrons/anil-kharia.jpg" },
  { name: "Mr. Amit Kumar Mishra", role: "Co-Patron", designation: "President", institution: "Chhattisgarh State Pharmacy Council, Raipur", image: "/committee/brochure/co-patrons/amit-kumar-mishra.jpg" },
  { name: "Mr. Piyush Jaiswal", role: "Co-Patron", designation: "Director", institution: "GDC, Bilaspur", image: "/committee/brochure/co-patrons/piyush-jaiswal.jpg" },
  { name: "Mr. Chinmay Davara", role: "Co-Patron", designation: "Founder and Chief Executive Officer (CEO)", institution: "Shri Davara University", image: "/committee/brochure/co-patrons/chinmay-davara.jpg" },
];

export const MENTORS: CommitteeMember[] = [
  { name: "Prof. V. K. Dixit", image: "/committee/brochure/mentors/v-k-dixit.jpg" },
  { name: "Dr. S. K. Kulkarni", image: "/committee/brochure/mentors/s-k-kulkarni.jpg" },
  { name: "Prof. C. K. Kokate", image: "/committee/brochure/mentors/c-k-kokate.jpg" },
  { name: "Prof. M. D. Karvekar", image: "/committee/brochure/mentors/m-d-karvekar.jpg" },
  { name: "Prof. S. P. Vyas", image: "/committee/brochure/mentors/s-p-vyas.jpg" },
  { name: "Prof. A. K. Singhai", image: "/committee/brochure/mentors/a-k-singhai.jpg" },
  { name: "Prof. S. C. Chaturvedi", image: "/committee/brochure/mentors/s-c-chaturvedi.jpg" },
  { name: "Prof. Piyush Trivedi", image: "/committee/brochure/mentors/piyush-trivedi.jpg" },
  { name: "Dr. Saranjeet Singh", image: "/committee/brochure/mentors/saranjeet-singh.jpg" },
  { name: "Prof. R. K. Khar", image: "/committee/brochure/mentors/r-k-khar.jpg" },
  { name: "Dr. V. Ravichandran", image: "/committee/brochure/mentors/v-ravichandran.jpg" },
  { name: "Prof. D. K. Jain", image: "/committee/brochure/mentors/d-k-jain.jpg" },
  { name: "Prof. S. K. Jain", image: "/committee/brochure/mentors/s-k-jain.jpg" },
  { name: "Dr. Sanjay Singh", image: "/committee/brochure/mentors/sanjay-singh.jpg" },
  { name: "Dr. O. P. Katare", image: "/committee/brochure/mentors/o-p-katare.jpg" },
  { name: "Prof. Shailendra Saraf", image: "/committee/brochure/mentors/shailendra-saraf.jpg" },
  { name: "Prof. Dulal Panda", image: "/committee/brochure/mentors/dulal-panda.jpg" },
  { name: "Dr. B. Mishra", image: "/committee/brochure/mentors/b-mishra.jpg" },
  { name: "Dr. Mahesh T. Chhabria", image: "/committee/brochure/mentors/mahesh-t-chhabria.jpg" },
  { name: "Dr. L. D. Patel", image: "/committee/brochure/mentors/l-d-patel.jpg" },
  { name: "Dr. C. T. Chopde", image: "/committee/brochure/mentors/c-t-chopde.jpg" },
  { name: "Dr. P. Vavia", image: "/committee/brochure/mentors/p-vavia.jpg" },
  { name: "Dr. S. Dhaneshwar", image: "/committee/brochure/mentors/s-dhaneshwar.jpg" },
  { name: "Dr. M. N. Saraf", image: "/committee/brochure/mentors/m-n-saraf.jpg" },
  { name: "Prof. B. G. Shivananda", image: "/committee/brochure/mentors/b-g-shivananda.jpg" },
  { name: "Dr. Devender Pathak", image: "/committee/brochure/mentors/devender-pathak.jpg" },
  { name: "Dr. Ajay Sachan", image: "/committee/brochure/mentors/ajay-sachan.jpg" },
  { name: "Dr. B. P. Nagori", image: "/committee/brochure/mentors/b-p-nagori.jpg" },
  { name: "Dr. P. G. Yeole", image: "/committee/brochure/mentors/p-g-yeole.jpg" },
  { name: "Dr. R. A. Gupta", image: "/committee/brochure/mentors/r-a-gupta.jpg" },
  { name: "Prof. S. C. Mahajan", image: "/committee/brochure/mentors/s-c-mahajan.jpg" },
  { name: "Dr. T. R. Sani", image: "/committee/brochure/mentors/t-r-sani.jpg" },
  { name: "Dr. Bhupinder Singh Bhoop", image: "/committee/brochure/mentors/bhupinder-singh-bhoop.jpg" },
  { name: "Dr. K. R. Mahadik", image: "/committee/brochure/mentors/k-r-mahadik.jpg" },
  { name: "Prof. R. K. Agrawal", image: "/committee/brochure/mentors/r-k-agrawal.jpg" },
  { name: "Prof. Subash Mandal", image: "/committee/brochure/mentors/subash-mandal.jpg" },
  { name: "Prof. R. S. Gaud", image: "/committee/brochure/mentors/r-s-gaud.jpg" },
];

export const INDUSTRY_PATRONS: CommitteeMember[] = [
  { name: "Mr. Ajit Singh", designation: "Chairman", institution: "ACG Capsules", image: "/committee/brochure/industry-patrons/ajit-singh.jpg" },
  { name: "Mr. Ravleen Singh Khurana", designation: "Managing Director", institution: "Nikita Pharmaceutical Specialities Pvt. Ltd, Nagpur", image: "/committee/brochure/industry-patrons/ravleen-singh-khurana.jpg" },
  { name: "Mr. M. E. Kannan", designation: "President (PTC)", institution: "Zydus Lifesciences", image: "/committee/brochure/industry-patrons/m-e-kannan.jpg" },
  { name: "Dr. Tushar Nahata", designation: "Senior General Manager", institution: "Zydus Lifesciences", image: "/committee/brochure/industry-patrons/tushar-nahata.jpg" },
  { name: "Shailendra Mandge", designation: "Chairman", institution: "ACG Capsules", image: "/committee/brochure/industry-patrons/shailendra-mandge.jpg" },
  { name: "Manish Agrawal", institution: "9M India Limited", image: "/committee/brochure/industry-patrons/manish-agrawal.jpg" },
  { name: "V. Vikramaditya Jain", designation: "Whole Time Director", institution: "Marksans Pharma Ltd", image: "/committee/brochure/industry-patrons/v-vikramaditya-jain.jpg" },
  { name: "Sunil Sharma", institution: "Sharma Ayurvedic Pharmacy", image: "/committee/brochure/industry-patrons/sunil-sharma.jpg" },
  { name: "Manoj Sharma", institution: "Sharma Ayurvedic Pharmacy", image: "/committee/brochure/industry-patrons/manoj-sharma.jpg" },
  { name: "Sanjeev Kumar Jain", designation: "Assistant General Manager", institution: "Torrent Pharma", image: "/committee/brochure/industry-patrons/sanjeev-kumar-jain.jpg" },
  { name: "Prateek Joshi", designation: "Director", institution: "Brainwave Healthcare Private Ltd.", image: "/committee/brochure/industry-patrons/prateek-joshi.jpg" },
  { name: "Vimal Mehta", institution: "Torrent Pharma", image: "/committee/brochure/industry-patrons/vimal-mehta.jpg" },
];

export const ACADEMIC_PARTNERS: CommitteeMember[] = [
  { name: "Mr. Praveen Vashistha", designation: "Chairman", institution: "MIT Group of Institutes, Ujjain", image: "/committee/brochure/academic-partners/praveen-vashistha.jpg" },
  { name: "Dr. Pushpendra S. Gautam", designation: "Chairman", institution: "Shri Krishna University, Chhatarpur (M.P.) & Aryavart University, Sehore (M.P.)", image: "/committee/brochure/academic-partners/pushpendra-s-gautam.jpg" },
  { name: "Mr. Toshan Chandrakar", designation: "Chairman", institution: "Royal College of Pharmacy, Raipur", image: "/committee/brochure/academic-partners/toshan-chandrakar.jpg" },
  { name: "Mr. Rahul Nahata", designation: "Executive Chairman", institution: "B. R. Nahata College of Pharmacy, Mandsaur University, Mandsaur", image: "/committee/brochure/academic-partners/rahul-nahata.jpg" },
  { name: "Er. Preeti Saluja", designation: "Chancellor", institution: "SAM Global University, Bhopal", image: "/committee/brochure/academic-partners/preeti-saluja.jpg" },
  { name: "Dr. Ajit Singh Patel", designation: "Pro Chancellor", institution: "Madhyanchal Professional University, Bhopal", image: "/committee/brochure/academic-partners/ajit-singh-patel.jpg" },
  { name: "Dr. Meena Chintamaneni", designation: "Pro-Vice Chancellor", institution: "SVKM's NMIMS Deemed-to-be University", image: "/committee/brochure/academic-partners/meena-chintamaneni.jpg" },
  { name: "Mr. Gaurav Bhadauria", designation: "Founder", institution: "Maharana Pratap Group of Institutions, Kanpur", image: "/committee/brochure/academic-partners/gaurav-bhadauria.jpg" },
  { name: "Mr. Harjeet Singh Hura", designation: "Pro-Chancellor", institution: "Columbia Professional University", image: "/committee/brochure/academic-partners/harjeet-singh-hura.jpg" },
  { name: "Mr. Pramod Jain", designation: "Chairman", institution: "LCIT Group of Institutions", image: "/committee/brochure/academic-partners/pramod-jain.jpg" },
  { name: "Er. B. S. Yadav", designation: "Chancellor", institution: "IES University, Bhopal", image: "/committee/brochure/academic-partners/b-s-yadav.jpg" },
  { name: "Mr. Ashish Jaiswal", designation: "Managing Director", institution: "Chouksey Group of Institutions, Bilaspur", image: "/committee/brochure/academic-partners/ashish-jaiswal.jpg" },
  { name: "Dr. Sudhir Bharadwaj", designation: "Director", institution: "Divine International Group of Institutions, Gwalior", image: "/committee/brochure/academic-partners/sudhir-bharadwaj.jpg" },
  { name: "Shri Abhishek Agrawal", designation: "Chancellor", institution: "Anjaneya University, Raipur", image: "/committee/brochure/academic-partners/abhishek-agrawal.jpg" },
  { name: "Shri Vinay Diwedi", designation: "Director Administration", institution: "Chhatrapati Shivaji Institute of Pharmacy, Durg", image: "/committee/brochure/academic-partners/vinay-diwedi.jpg" },
  { name: "Er. K. Khan", designation: "Chairman", institution: "J. K. Group of Institutions, Bilaspur", image: "/committee/brochure/academic-partners/k-khan.jpg" },
  { name: "Dr. Dharmendra Ahuja", designation: "Principal Mentor", institution: "Experimental Pharmacology Software, BHESU (India)", image: "/committee/brochure/academic-partners/dharmendra-ahuja.jpg" },
  { name: "Dr. Anurag Jain", designation: "Executive Member", institution: "Gracious College of Pharmacy", image: "/committee/brochure/academic-partners/anurag-jain.jpg" },
  { name: "Mr. Sunil Pandya", designation: "Chairman", institution: "Parijat Group of Institutions, Indore", image: "/committee/brochure/academic-partners/sunil-pandya.jpg" },
  { name: "Shri Gaurav Thakral", designation: "Vice Chairman & Pro Chancellor", institution: "Oriental Group of Institutions, Bhopal & Oriental University, Indore", image: "/committee/brochure/academic-partners/gaurav-thakral.jpg" },
];

export const PCI_MEMBERS: CommitteeMember[] = [
  { name: "Mr. Jashubhai Hirabhai Chaudhari", image: "/committee/brochure/pci-members/jashubhai-hirabhai-chaudhari.jpg" },
  { name: "Prof. B. Jayakar", image: "/committee/brochure/pci-members/b-jayakar.jpg" },
  { name: "Dr. Atul Kumar Nasa", image: "/committee/brochure/pci-members/atul-kumar-nasa.jpg" },
  { name: "Shri Dharmendra Singh", image: "/committee/brochure/pci-members/dharmendra-singh.jpg" },
  { name: "Dr. H. Lalhlenmawia", image: "/committee/brochure/pci-members/h-lalhlenmawia.jpg" },
  { name: "Shri Sushil Kumar Bansal", image: "/committee/brochure/pci-members/sushil-kumar-bansal.jpg" },
  { name: "Shri J. S. Shinde", image: "/committee/brochure/pci-members/j-s-shinde.jpg" },
  { name: "Prof. Sanjay Singh", image: "/committee/brochure/pci-members/sanjay-singh.jpg" },
  { name: "Prof. (Dr.) Akash Ved", image: "/committee/brochure/pci-members/akash-ved.jpg" },
  { name: "Shri Vijay Pandurang Patil", image: "/committee/brochure/pci-members/vijay-pandurang-patil.jpg" },
  { name: "Dr. Anand Mahalwar", image: "/committee/brochure/pci-members/anand-mahalwar.jpg" },
  { name: "Shri Sanjay Kumar Jain", image: "/committee/brochure/pci-members/sanjay-kumar-jain.jpg" },
  { name: "Dr. M. Venkata Ramana", image: "/committee/brochure/pci-members/m-venkata-ramana.jpg" },
  { name: "Mr. Gopal Krishan Sharma", image: "/committee/brochure/pci-members/gopal-krishan-sharma.jpg" },
  { name: "Shri Sushil Sudan", image: "/committee/brochure/pci-members/sushil-sudan.jpg" },
  { name: "Dr. Neeraj Upmanyu", image: "/committee/brochure/pci-members/neeraj-upmanyu.jpg" },
  { name: "Shri Prakash Jeevandas Wanjari", image: "/committee/brochure/pci-members/prakash-jeevandas-wanjari.jpg" },
  { name: "Dr. Sanjay Toshniwal", image: "/committee/brochure/pci-members/sanjay-toshniwal.jpg" },
  { name: "Dr. Narendra Devanaboyina", image: "/committee/brochure/pci-members/narendra-devanaboyina.jpg" },
  { name: "Prof. Dr. Nilimanka Das", image: "/committee/brochure/pci-members/nilimanka-das.jpg" },
  { name: "Shri Mohd Bashir", image: "/committee/brochure/pci-members/mohd-bashir.jpg" },
  { name: "Dr. Sarat Chandran", image: "/committee/brochure/pci-members/sarat-chandran.jpg" },
  { name: "Prof. (Dr.) Vibhu Sahani", image: "/committee/brochure/pci-members/vibhu-sahani.jpg" },
  { name: "Shri Dhanesh Adlakha", image: "/committee/brochure/pci-members/dhanesh-adlakha.jpg" },
  { name: "Dr. S. Kavimani", image: "/committee/brochure/pci-members/s-kavimani.jpg" },
  { name: "Prof. Sanjay Singh", image: "/committee/brochure/pci-members/sanjay-singh-2.jpg" },
  { name: "Dr. Shrikant Vijayrao Joshi", image: "/committee/brochure/pci-members/shrikant-vijayrao-joshi.jpg" },
  { name: "Dr. Saleemulla Khan", image: "/committee/brochure/pci-members/saleemulla-khan.jpg" },
  { name: "Shri Sunil Kumar Chaudhary", image: "/committee/brochure/pci-members/sunil-kumar-chaudhary.jpg" },
  { name: "Dr. Nepram Swarnalata", image: "/committee/brochure/pci-members/nepram-swarnalata.jpg" },
  { name: "Sri Kumar Ajay", image: "/committee/brochure/pci-members/kumar-ajay.jpg" },
  { name: "Dr. Ashvin V. Dudhrejiya", image: "/committee/brochure/pci-members/ashvin-v-dudhrejiya.jpg" },
  { name: "Smt. Shweta S. Dessai", image: "/committee/brochure/pci-members/shweta-s-dessai.jpg" },
  { name: "Dr. S. L. N. Prasad Reddy", image: "/committee/brochure/pci-members/s-l-n-prasad-reddy.jpg" },
  { name: "Shri Sudhir Chandra Saha", image: "/committee/brochure/pci-members/sudhir-chandra-saha.jpg" },
  { name: "Mrs. Irfana Ahmed", image: "/committee/brochure/pci-members/irfana-ahmed.jpg" },
  { name: "Shri Jyotiprakash Nanda", image: "/committee/brochure/pci-members/jyotiprakash-nanda.jpg" },
  { name: "Shri Surinder Mohan", image: "/committee/brochure/pci-members/surinder-mohan.jpg" },
  { name: "Shri Antony Laloo", image: "/committee/brochure/pci-members/antony-laloo.jpg" },
  { name: "Mr. Ratnadeep Kurtarkar", image: "/committee/brochure/pci-members/ratnadeep-kurtarkar.jpg" },
  { name: "Shri Sukhvinder Pal", image: "/committee/brochure/pci-members/sukhvinder-pal.jpg" },
  { name: "Shri Naveenchand O. C.", image: "/committee/brochure/pci-members/naveenchand-o-c.jpg" },
  { name: "Dr. P. Sathiamurthi", image: "/committee/brochure/pci-members/p-sathiamurthi.jpg" },
  { name: "Dr. Veera Reddy Prabhakar Reddy", image: "/committee/brochure/pci-members/veera-reddy-prabhakar-reddy.jpg" },
  { name: "Mr. Dinesh Kumar Madan", image: "/committee/brochure/pci-members/dinesh-kumar-madan.jpg" },
  { name: "Dr. Shivanand Malakappa Patil", image: "/committee/brochure/pci-members/shivanand-malakappa-patil.jpg" },
  { name: "Shri Debasish Bhattacharjee", image: "/committee/brochure/pci-members/debasish-bhattacharjee.jpg" },
  { name: "Shri Nilamadhab Dash", image: "/committee/brochure/pci-members/nilamadhab-dash.jpg" },
  { name: "Shri Sandeep Badola", image: "/committee/brochure/pci-members/sandeep-badola.jpg" },
  { name: "Miss Gyati Siri", image: "/committee/brochure/pci-members/gyati-siri.jpg" },
  { name: "Dr. Tarun Kanti Ghosh", image: "/committee/brochure/pci-members/tarun-kanti-ghosh.jpg" },
  { name: "Sri N. Rimot Kumar Meetei", image: "/committee/brochure/pci-members/n-rimot-kumar-meetei.jpg" },
  { name: "Shri Iarap T. D. Toi", image: "/committee/brochure/pci-members/iarap-t-d-toi.jpg" },
  { name: "Prof. Dr. Rishi Raj Chhetree", image: "/committee/brochure/pci-members/rishi-raj-chhetree.jpg" },
  { name: "Dr. Mannava Radhakrishna Murthy M.D.", image: "/committee/brochure/pci-members/mannava-radhakrishna-murthy-m-d.jpg" },
  { name: "Shri Lyangain Martin Targain", image: "/committee/brochure/pci-members/lyangain-martin-targain.jpg" },
  { name: "Baldev Kumar", image: "/committee/brochure/pci-members/baldev-kumar.jpg" },
  { name: "Dr. Padma Charan Behera", image: "/committee/brochure/pci-members/padma-charan-behera.jpg" },
  { name: "Shri Naveen Sanghi", image: "/committee/brochure/pci-members/naveen-sanghi.jpg" },
  { name: "Sri Khele Thorie", image: "/committee/brochure/pci-members/khele-thorie.jpg" },
  { name: "Sri Navneet Marwaha", image: "/committee/brochure/pci-members/navneet-marwaha.jpg" },
  { name: "Shri Sohan Lal Kansal", image: "/committee/brochure/pci-members/sohan-lal-kansal.jpg" },
];

export const NATIONAL_ADVISORS: CommitteeMember[] = [
  { name: "Dr. Rakesh Somani", image: "/committee/brochure/national-advisors/rakesh-somani.jpg" },
  { name: "Dr. Pawan Dubey", image: "/committee/brochure/national-advisors/pawan-dubey.jpg" },
  { name: "Prof. Ranjit Singh", image: "/committee/brochure/national-advisors/ranjit-singh.jpg" },
  { name: "Dr. Satish Nayak", image: "/committee/brochure/national-advisors/satish-nayak.jpg" },
  { name: "Ashwini Gurdekar", image: "/committee/brochure/national-advisors/ashwini-gurdekar.jpg" },
  { name: "Dr. Surendra Bhodkhe", image: "/committee/brochure/national-advisors/surendra-bhodkhe.jpg" },
  { name: "Dr. U. K. Patil", image: "/committee/brochure/national-advisors/u-k-patil.jpg" },
  { name: "Dr. Umesh Jain", image: "/committee/brochure/national-advisors/umesh-jain.jpg" },
  { name: "Mr. Praveen Garg", image: "/committee/brochure/national-advisors/praveen-garg.jpg" },
  { name: "Dr. Vimal Kumar Jain", image: "/committee/brochure/national-advisors/vimal-kumar-jain.jpg" },
  { name: "Prof. A. K. Singhai", image: "/committee/brochure/national-advisors/a-k-singhai.jpg" },
  { name: "Dr. N. V. V. Jagan Mohan Reddy", image: "/committee/brochure/national-advisors/n-v-v-jagan-mohan-reddy.jpg" },
  { name: "Prof. Sushant Srivastava", image: "/committee/brochure/national-advisors/sushant-srivastava.jpg" },
  { name: "Prof. Arun Garg", image: "/committee/brochure/national-advisors/arun-garg.jpg" },
  { name: "Prof. Kamlesh Dashora", image: "/committee/brochure/national-advisors/kamlesh-dashora.jpg" },
  { name: "Dr. Swarnalata Saraf", image: "/committee/brochure/national-advisors/swarnalata-saraf.jpg" },
  { name: "Prof. Preeti K. Suresh", image: "/committee/brochure/national-advisors/preeti-k-suresh.jpg" },
  { name: "Dr. Sanjay Jain", image: "/committee/brochure/national-advisors/sanjay-jain.jpg" },
  { name: "Prof. S. J. Daharwal", image: "/committee/brochure/national-advisors/s-j-daharwal.jpg" },
  { name: "Dr. Gaurav Kaithwas", image: "/committee/brochure/national-advisors/gaurav-kaithwas.jpg" },
  { name: "Dr. Alok Mukharjee", image: "/committee/brochure/national-advisors/alok-mukharjee.jpg" },
  { name: "Dr. Anil Mittal", image: "/committee/brochure/national-advisors/anil-mittal.jpg" },
  { name: "Dr. Pratima Tiwari", image: "/committee/brochure/national-advisors/pratima-tiwari.jpg" },
  { name: "Prof. (Dr.) Divya Juyal", image: "/committee/brochure/national-advisors/divya-juyal.jpg" },
  { name: "Dr. Preeti Kothiyal", image: "/committee/brochure/national-advisors/preeti-kothiyal.jpg" },
  { name: "Prof. Gajendra Singh", image: "/committee/brochure/national-advisors/gajendra-singh.jpg" },
  { name: "Dr. Pulok Mukherjee", image: "/committee/brochure/national-advisors/pulok-mukherjee.jpg" },
  { name: "Dr. Om Shilakari", image: "/committee/brochure/national-advisors/om-shilakari.jpg" },
  { name: "Dr. Manish Chaurasia", image: "/committee/brochure/national-advisors/manish-chaurasia.jpg" },
  { name: "Dr. Kamla Pathak", image: "/committee/brochure/national-advisors/kamla-pathak.jpg" },
  { name: "Dr. K. P. Namdeo", image: "/committee/brochure/national-advisors/k-p-namdeo.jpg" },
  { name: "Dr. Hema Dullar", image: "/committee/brochure/national-advisors/hema-dullar.jpg" },
  { name: "Dr. Susanta Kumar Panda", image: "/committee/brochure/national-advisors/susanta-kumar-panda.jpg" },
  { name: "Dr. Hemant Jain", image: "/committee/brochure/national-advisors/hemant-jain.jpg" },
  { name: "Dr. G. J. Jeyabalan", image: "/committee/brochure/national-advisors/g-j-jeyabalan.jpg" },
  { name: "Dr. Hemant Joshi", image: "/committee/brochure/national-advisors/hemant-joshi.jpg" },
  { name: "Dr. Deepti Jain", image: "/committee/brochure/national-advisors/deepti-jain.jpg" },
  { name: "Dr. Chetan Singh Chauhan", image: "/committee/brochure/national-advisors/chetan-singh-chauhan.jpg" },
  { name: "Dr. C. A. Doifode", image: "/committee/brochure/national-advisors/c-a-doifode.jpg" },
  { name: "Dr. C. D. Upasani", image: "/committee/brochure/national-advisors/c-d-upasani.jpg" },
  { name: "Dr. Ashok Dashora", image: "/committee/brochure/national-advisors/ashok-dashora.jpg" },
  { name: "Prof. Vijay Juyal", image: "/committee/brochure/national-advisors/vijay-juyal.jpg" },
  { name: "Dr. Basavaraj Nanjwade", image: "/committee/brochure/national-advisors/basavaraj-nanjwade.jpg" },
  { name: "Dr. Arun Kumar Gupta", image: "/committee/brochure/national-advisors/arun-kumar-gupta.jpg" },
  { name: "Dr. Anju Goyal", image: "/committee/brochure/national-advisors/anju-goyal.jpg" },
  { name: "Dr. Alka Mukane", image: "/committee/brochure/national-advisors/alka-mukane.jpg" },
  { name: "Dr. Sanmati Kumar Jain", image: "/committee/brochure/national-advisors/sanmati-kumar-jain.jpg" },
  { name: "Dr. Abhay Dharamsi", image: "/committee/brochure/national-advisors/abhay-dharamsi.jpg" },
  { name: "Dr. Rajesh Singh Pawar", image: "/committee/brochure/national-advisors/rajesh-singh-pawar.jpg" },
  { name: "Dr. Kamal Singh Rathore", image: "/committee/brochure/national-advisors/kamal-singh-rathore.jpg" },
  { name: "Dr. Kamlesh Wadher", image: "/committee/brochure/national-advisors/kamlesh-wadher.jpg" },
  { name: "Dr. M. S. Ashawat", image: "/committee/brochure/national-advisors/m-s-ashawat.jpg" },
  { name: "Dr. Meena Tiwari", image: "/committee/brochure/national-advisors/meena-tiwari.jpg" },
  { name: "Dr. Praful Sabale", image: "/committee/brochure/national-advisors/praful-sabale.jpg" },
  { name: "Dr. Munira Momin", image: "/committee/brochure/national-advisors/munira-momin.jpg" },
  { name: "Dr. Monica Gulati", image: "/committee/brochure/national-advisors/monica-gulati.jpg" },
  { name: "Dr. Neha Kauwathekar", image: "/committee/brochure/national-advisors/neha-kauwathekar.jpg" },
  { name: "Dr. P. K. Sahoo", image: "/committee/brochure/national-advisors/p-k-sahoo.jpg" },
  { name: "Dr. Pankaj Agrawal", image: "/committee/brochure/national-advisors/pankaj-agrawal.jpg" },
  { name: "Dr. Rajesh Yadav", image: "/committee/brochure/national-advisors/rajesh-yadav.jpg" },
  { name: "Dr. Prakash Itankar", image: "/committee/brochure/national-advisors/prakash-itankar.jpg" },
  { name: "Dr. R. K. Maheswari", image: "/committee/brochure/national-advisors/r-k-maheswari.jpg" },
  { name: "Dr. Rajendra Kakde", image: "/committee/brochure/national-advisors/rajendra-kakde.jpg" },
  { name: "Dr. Rajesh Goyal", image: "/committee/brochure/national-advisors/rajesh-goyal.jpg" },
  { name: "Dr. Rajesh Sharma", image: "/committee/brochure/national-advisors/rajesh-sharma.jpg" },
  { name: "Dr. Bharti Ahirwar", image: "/committee/brochure/national-advisors/bharti-ahirwar.jpg" },
  { name: "Dr. S. S. Sisodia", image: "/committee/brochure/national-advisors/s-s-sisodia.jpg" },
  { name: "Dr. Sanjay Chauhan", image: "/committee/brochure/national-advisors/sanjay-chauhan.jpg" },
  { name: "Dr. Sanjay Surana", image: "/committee/brochure/national-advisors/sanjay-surana.jpg" },
  { name: "Dr. Shubheet Jain", image: "/committee/brochure/national-advisors/shubheet-jain.jpg" },
  { name: "Dr. Dilip Pal", image: "/committee/brochure/national-advisors/dilip-pal.jpg" },
  { name: "Dr. G. N. Darwhekar", image: "/committee/brochure/national-advisors/g-n-darwhekar.jpg" },
  { name: "Dr. Divakar Goli", image: "/committee/brochure/national-advisors/divakar-goli.jpg" },
  { name: "Dr. G. D. Gupta", image: "/committee/brochure/national-advisors/g-d-gupta.jpg" },
  { name: "Dr. Havagiray Chitme", image: "/committee/brochure/national-advisors/havagiray-chitme.jpg" },
  { name: "Dr. Indupal Kaur", image: "/committee/brochure/national-advisors/indupal-kaur.jpg" },
  { name: "Dr. N. P. Yadav", image: "/committee/brochure/national-advisors/n-p-yadav.jpg" },
  { name: "Dr. Nishith M. C.", image: "/committee/brochure/national-advisors/nishith-m-c.jpg" },
  { name: "Dr. Kamlesh Nayak", image: "/committee/brochure/national-advisors/kamlesh-nayak.jpg" },
  { name: "Dr. Kumud Upadhyaya", image: "/committee/brochure/national-advisors/kumud-upadhyaya.jpg" },
  { name: "Dr. M. L. Kori", image: "/committee/brochure/national-advisors/m-l-kori.jpg" },
  { name: "Dr. Mohan Kale", image: "/committee/brochure/national-advisors/mohan-kale.jpg" },
  { name: "Dr. R. Kalirajan", image: "/committee/brochure/national-advisors/r-kalirajan.jpg" },
  { name: "Dr. Rajendra Bhamber", image: "/committee/brochure/national-advisors/rajendra-bhamber.jpg" },
  { name: "Dr. Nitin Deore", image: "/committee/brochure/national-advisors/nitin-deore.jpg" },
  { name: "Dr. Praful Bharadia", image: "/committee/brochure/national-advisors/praful-bharadia.jpg" },
  { name: "Dr. R. Marathe", image: "/committee/brochure/national-advisors/r-marathe.jpg" },
  { name: "Dr. Sanjay Jachak", image: "/committee/brochure/national-advisors/sanjay-jachak.jpg" },
  { name: "Dr. Sanjeev Mittal", image: "/committee/brochure/national-advisors/sanjeev-mittal.jpg" },
  { name: "Dr. Satish A. Kavatagimath", image: "/committee/brochure/national-advisors/satish-a-kavatagimath.jpg" },
  { name: "Dr. S. Vidyadhara", image: "/committee/brochure/national-advisors/s-vidyadhara.jpg" },
  { name: "Dr. S. Wakode", image: "/committee/brochure/national-advisors/s-wakode.jpg" },
  { name: "Dr. Srinivas Mutalik", image: "/committee/brochure/national-advisors/srinivas-mutalik.jpg" },
  { name: "Dr. Sudarshan Biswal", image: "/committee/brochure/national-advisors/sudarshan-biswal.jpg" },
  { name: "Dr. Sukriti Das", image: "/committee/brochure/national-advisors/sukriti-das.jpg" },
  { name: "Dr. Suman Jain", image: "/committee/brochure/national-advisors/suman-jain.jpg" },
  { name: "Dr. Sayeed Ahmed", image: "/committee/brochure/national-advisors/sayeed-ahmed.jpg" },
  { name: "Dr. Shamim Ahmad", image: "/committee/brochure/national-advisors/shamim-ahmad.jpg" },
  { name: "Dr. Suneela Dhaneshwar", image: "/committee/brochure/national-advisors/suneela-dhaneshwar.jpg" },
  { name: "Dr. Surendra Jain", image: "/committee/brochure/national-advisors/surendra-jain.jpg" },
  { name: "Dr. Suresh Thakur", image: "/committee/brochure/national-advisors/suresh-thakur.jpg" },
  { name: "Dr. Tanveer Naved", image: "/committee/brochure/national-advisors/tanveer-naved.jpg" },
  { name: "Dr. Vijay Bhalla", image: "/committee/brochure/national-advisors/vijay-bhalla.jpg" },
  { name: "Mr. Rajesh Chaudhari", image: "/committee/brochure/national-advisors/rajesh-chaudhari.jpg" },
  { name: "Prof. Amiyakanta Mishra", image: "/committee/brochure/national-advisors/amiyakanta-mishra.jpg" },
  { name: "Prof. Pawan Krishan Patiala", image: "/committee/brochure/national-advisors/pawan-krishan-patiala.jpg" },
  { name: "Prof. Rajesh Neema", image: "/committee/brochure/national-advisors/rajesh-neema.jpg" },
  { name: "Prof. Rama Rao Nadendla", image: "/committee/brochure/national-advisors/rama-rao-nadendla.jpg" },
  { name: "Dr. Yuvraj Singh Sarangdevot", image: "/committee/brochure/national-advisors/yuvraj-singh-sarangdevot.jpg" },
  { name: "Prof. Sunil S. Jalalpure", image: "/committee/brochure/national-advisors/sunil-s-jalalpure.jpg" },
  { name: "Prof. Vandana Arora Sethi", image: "/committee/brochure/national-advisors/vandana-arora-sethi.jpg" },
  { name: "Shri Dilip G.", image: "/committee/brochure/national-advisors/dilip-g.jpg" },
  { name: "Shri Tapan Kumar Choudhary", image: "/committee/brochure/national-advisors/tapan-kumar-choudhary.jpg" },
  { name: "Prof. Ravindra D. Hiremath", image: "/committee/brochure/national-advisors/ravindra-d-hiremath.jpg" },
  { name: "Shri Anil Kumar Negi", image: "/committee/brochure/national-advisors/anil-kumar-negi.jpg" },
  { name: "Shri Bhanu Dua", image: "/committee/brochure/national-advisors/bhanu-dua.jpg" },
  { name: "Shri Bharat Bhushan", image: "/committee/brochure/national-advisors/bharat-bhushan.jpg" },
  { name: "Shri P. P. Sharma", image: "/committee/brochure/national-advisors/p-p-sharma.jpg" },
  { name: "Shri Pawan Kumar Jaggi", image: "/committee/brochure/national-advisors/pawan-kumar-jaggi.jpg" },
  { name: "Shri Sudhir Kumar Singh Shastradhar", image: "/committee/brochure/national-advisors/sudhir-kumar-singh-shastradhar.jpg" },
  { name: "Dr. Dinesh Chaple", image: "/committee/brochure/national-advisors/dinesh-chaple.jpg" },
  { name: "Dr. Ashmita Gajbhiye", image: "/committee/brochure/national-advisors/ashmita-gajbhiye.jpg" },
  { name: "Dr. N. S. Hari Narayana Moorthy", image: "/committee/brochure/national-advisors/n-s-hari-narayana-moorthy.jpg" },
  { name: "Dr. Manish Chaurasia", image: "/committee/brochure/national-advisors/manish-chaurasia-2.jpg" },
  { name: "Dr. Prem Nath Shenoy", image: "/committee/brochure/national-advisors/prem-nath-shenoy.jpg" },
  { name: "Dr. Sanjay Bari", image: "/committee/brochure/national-advisors/sanjay-bari.jpg" },
  { name: "Prof. A. K. Madan", image: "/committee/brochure/national-advisors/a-k-madan.jpg" },
  { name: "Dr. Atul Shirkhedkar", image: "/committee/brochure/national-advisors/atul-shirkhedkar.jpg" },
  { name: "Dr. Himanshu Manjhi", image: "/committee/brochure/national-advisors/himanshu-manjhi.jpg" },
  { name: "Mr. K. Mruthunjaya", image: "/committee/brochure/national-advisors/k-mruthunjaya.jpg" },
  { name: "Dr. Gurudutta Pattnaik", image: "/committee/brochure/national-advisors/gurudutta-pattnaik.jpg" },
  { name: "Prof. Dr. Subhashree Sahoo", image: "/committee/brochure/national-advisors/subhashree-sahoo.jpg" },
  { name: "Mr. Rajesh Trivedi", image: "/committee/brochure/national-advisors/rajesh-trivedi.jpg" },
  { name: "Shri Lalit Kumar Goel", image: "/committee/brochure/national-advisors/lalit-kumar-goel.jpg" },
  { name: "Dr. A. Ramkishan", image: "/committee/brochure/national-advisors/a-ramkishan.jpg" },
  { name: "Dr. S. P. Dhanabal", image: "/committee/brochure/national-advisors/s-p-dhanabal.jpg" },
  { name: "Prof. Kanchan Kohli", image: "/committee/brochure/national-advisors/kanchan-kohli.jpg" },
  { name: "Dr. R. R. Raghavendra", image: "/committee/brochure/national-advisors/r-r-raghavendra.jpg" },
  { name: "Dr. Dinesh Biyani", image: "/committee/brochure/national-advisors/dinesh-biyani.jpg" },
  { name: "Dr. Nimisha Jain", image: "/committee/brochure/national-advisors/nimisha-jain.jpg" },
  { name: "Prof. Raj Kumar Narang", image: "/committee/brochure/national-advisors/raj-kumar-narang.jpg" },
  { name: "Dr. Sourabh Kosey", image: "/committee/brochure/national-advisors/sourabh-kosey.jpg" },
  { name: "Dr. Arvind Karadi", image: "/committee/brochure/national-advisors/arvind-karadi.jpg" },
  { name: "Dr. Sukhbir Lal", image: "/committee/brochure/national-advisors/sukhbir-lal.jpg" },
];

export const YOUNG_LEADERSHIP: CommitteeMember[] = [
  { name: "Prof. Sushil Kumar Kashav", image: "/committee/brochure/young-leadership/sushil-kumar-kashav.jpg" },
  { name: "Dr. Puneet Bansal", image: "/committee/brochure/young-leadership/puneet-bansal.jpg" },
  { name: "Prof. Ashish Baldi", image: "/committee/brochure/young-leadership/ashish-baldi.jpg" },
  { name: "Dr. Vandana Dutt", image: "/committee/brochure/young-leadership/vandana-dutt.jpg" },
  { name: "Dr. Nimita Minocha", image: "/committee/brochure/young-leadership/nimita-minocha.jpg" },
  { name: "Dr. Alpana Ram", image: "/committee/brochure/young-leadership/alpana-ram.jpg" },
  { name: "Dr. Pranay Wal", image: "/committee/brochure/young-leadership/pranay-wal.jpg" },
  { name: "Dr. Thakur Gurjeet Singh", image: "/committee/brochure/young-leadership/thakur-gurjeet-singh.jpg" },
  { name: "Dr. Vishal Garg", image: "/committee/brochure/young-leadership/vishal-garg.jpg" },
  { name: "Dr. Mahendra Rana", image: "/committee/brochure/young-leadership/mahendra-rana.jpg" },
  { name: "Dr. Juhi Pradhan", image: "/committee/brochure/young-leadership/juhi-pradhan.jpg" },
  { name: "Dr. Dhirendar Kaushik", image: "/committee/brochure/young-leadership/dhirendar-kaushik.jpg" },
  { name: "Dr. Ankita Wal", image: "/committee/brochure/young-leadership/ankita-wal.jpg" },
  { name: "Dr. Vishal Gupta", image: "/committee/brochure/young-leadership/vishal-gupta.jpg" },
  { name: "Dr. Pushpendra Singh Naruka", image: "/committee/brochure/young-leadership/pushpendra-singh-naruka.jpg" },
  { name: "Dr. Vishal Subhash Chand Gulecha", image: "/committee/brochure/young-leadership/vishal-subhash-chand-gulecha.jpg" },
  { name: "Dr. Ganesh Narayan Sharma", image: "/committee/brochure/young-leadership/ganesh-narayan-sharma.jpg" },
  { name: "Dr. Goutam Rath", image: "/committee/brochure/young-leadership/goutam-rath.jpg" },
  { name: "Dr. Sweta Kapoor", image: "/committee/brochure/young-leadership/sweta-kapoor.jpg" },
  { name: "Dr. Amit Kumar Nigam", image: "/committee/brochure/young-leadership/amit-kumar-nigam.jpg" },
  { name: "Dr. Lubhan Singh", image: "/committee/brochure/young-leadership/lubhan-singh.jpg" },
  { name: "Dr. Kamal Shah", image: "/committee/brochure/young-leadership/kamal-shah.jpg" },
  { name: "Dr. Satyendra Singh", image: "/committee/brochure/young-leadership/satyendra-singh.jpg" },
  { name: "Dr. Saloni Kakkar", image: "/committee/brochure/young-leadership/saloni-kakkar.jpg" },
  { name: "Dr. Jagdish R. Baheti", image: "/committee/brochure/young-leadership/jagdish-r-baheti.jpg" },
  { name: "Dr. Rakesh Chawla", image: "/committee/brochure/young-leadership/rakesh-chawla.jpg" },
  { name: "Dr. Vikash Jakmola", image: "/committee/brochure/young-leadership/vikash-jakmola.jpg" },
  { name: "Dr. Bhushan Kumar Sathe", image: "/committee/brochure/young-leadership/bhushan-kumar-sathe.jpg" },
  { name: "Dr. Ashish Srivastava", image: "/committee/brochure/young-leadership/ashish-srivastava.jpg" },
  { name: "Dr. Deepak Kaushik", image: "/committee/brochure/young-leadership/deepak-kaushik.jpg" },
  { name: "Dr. K. S. Shukla", image: "/committee/brochure/young-leadership/k-s-shukla.jpg" },
  { name: "Dr. Manju Pandey", image: "/committee/brochure/young-leadership/manju-pandey.jpg" },
  { name: "Dr. Namrata Singh", image: "/committee/brochure/young-leadership/namrata-singh.jpg" },
  { name: "Dr. Alok Shukla", image: "/committee/brochure/young-leadership/alok-shukla.jpg" },
  { name: "Dr. Manish Mishra", image: "/committee/brochure/young-leadership/manish-mishra.jpg" },
  { name: "Dr. Sunil Prajapati", image: "/committee/brochure/young-leadership/sunil-prajapati.jpg" },
  { name: "Dr. Amit Alexander", image: "/committee/brochure/young-leadership/amit-alexander.jpg" },
  { name: "Dr. Amar Jhalte", image: "/committee/brochure/young-leadership/amar-jhalte.jpg" },
  { name: "Dr. Amit Goyal", image: "/committee/brochure/young-leadership/amit-goyal.jpg" },
  { name: "Dr. Amit Jain", image: "/committee/brochure/young-leadership/amit-jain.jpg" },
  { name: "Dr. Aviral Jain", image: "/committee/brochure/young-leadership/aviral-jain.jpg" },
  { name: "Dr. Mahesh Prasad", image: "/committee/brochure/young-leadership/mahesh-prasad.jpg" },
  { name: "Dr. Biplab Debnath", image: "/committee/brochure/young-leadership/biplab-debnath.jpg" },
  { name: "Dr. Geeta Deswal", image: "/committee/brochure/young-leadership/geeta-deswal.jpg" },
  { name: "Dr. Kumar Gaurve", image: "/committee/brochure/young-leadership/kumar-gaurve.jpg" },
  { name: "Dr. Jayesh Dwivedi", image: "/committee/brochure/young-leadership/jayesh-dwivedi.jpg" },
  { name: "Dr. Mohamad Asif", image: "/committee/brochure/young-leadership/mohamad-asif.jpg" },
  { name: "Dr. Manoj Kumar Goyal", image: "/committee/brochure/young-leadership/manoj-kumar-goyal.jpg" },
  { name: "Dr. Nishikant Raut", image: "/committee/brochure/young-leadership/nishikant-raut.jpg" },
  { name: "Dr. Nitin Haswani", image: "/committee/brochure/young-leadership/nitin-haswani.jpg" },
  { name: "Dr. Parimal P. Katolkar", image: "/committee/brochure/young-leadership/parimal-p-katolkar.jpg" },
  { name: "Dr. Parijat Pandey", image: "/committee/brochure/young-leadership/parijat-pandey.jpg" },
  { name: "Dr. Priti Tagade", image: "/committee/brochure/young-leadership/priti-tagade.jpg" },
  { name: "Dr. Rahul Pratap Singh", image: "/committee/brochure/young-leadership/rahul-pratap-singh.jpg" },
  { name: "Dr. Reetesh Yadav", image: "/committee/brochure/young-leadership/reetesh-yadav.jpg" },
  { name: "Dr. Sachin Jain", image: "/committee/brochure/young-leadership/sachin-jain.jpg" },
  { name: "Dr. Shivkant Sharma", image: "/committee/brochure/young-leadership/shivkant-sharma.jpg" },
  { name: "Dr. Sushil Bhargav", image: "/committee/brochure/young-leadership/sushil-bhargav.jpg" },
  { name: "Dr. Tarun Virmani", image: "/committee/brochure/young-leadership/tarun-virmani.jpg" },
  { name: "Dr. Vihangesh Kumar Dixit", image: "/committee/brochure/young-leadership/vihangesh-kumar-dixit.jpg" },
  { name: "Dr. Udichi Kataraia", image: "/committee/brochure/young-leadership/udichi-kataraia.jpg" },
  { name: "Dr. Vikas Kumar Singh", image: "/committee/brochure/young-leadership/vikas-kumar-singh.jpg" },
  { name: "Dr. Vikram Kumar Sahu", image: "/committee/brochure/young-leadership/vikram-kumar-sahu.jpg" },
  { name: "Dr. Vipin Dhote", image: "/committee/brochure/young-leadership/vipin-dhote.jpg" },
  { name: "Dr. Vinesh Kumar", image: "/committee/brochure/young-leadership/vinesh-kumar.jpg" },
  { name: "Dr. Vipin Sharma", image: "/committee/brochure/young-leadership/vipin-sharma.jpg" },
  { name: "Dr. Yogendra Mavai", image: "/committee/brochure/young-leadership/yogendra-mavai.jpg" },
  { name: "Dr. Yogesh Bafana", image: "/committee/brochure/young-leadership/yogesh-bafana.jpg" },
  { name: "Dr. Yuvraj Dangi", image: "/committee/brochure/young-leadership/yuvraj-dangi.jpg" },
  { name: "Dr. Gulshan Gurunani", image: "/committee/brochure/young-leadership/gulshan-gurunani.jpg" },
  { name: "Dr. Biren N. Shah", image: "/committee/brochure/young-leadership/biren-n-shah.jpg" },
  { name: "Dr. Kalpesh Gour", image: "/committee/brochure/young-leadership/kalpesh-gour.jpg" },
  { name: "Dr. Kapil Agrawal", image: "/committee/brochure/young-leadership/kapil-agrawal.jpg" },
  { name: "Dr. Masheer Ahmed Khan", image: "/committee/brochure/young-leadership/masheer-ahmed-khan.jpg" },
  { name: "Dr. Prashant Mathur", image: "/committee/brochure/young-leadership/prashant-mathur.jpg" },
  { name: "Dr. Pradeep Singore", image: "/committee/brochure/young-leadership/pradeep-singore.jpg" },
  { name: "Mr. Sachin W. Lohe", image: "/committee/brochure/young-leadership/sachin-w-lohe.jpg" },
  { name: "Prof. Ajay K. Gupta", image: "/committee/brochure/young-leadership/ajay-k-gupta.jpg" },
  { name: "Dr. Nitin G. Dumore", image: "/committee/brochure/young-leadership/nitin-g-dumore.jpg" },
  { name: "Dr. Tirupati M. Rasala", image: "/committee/brochure/young-leadership/tirupati-m-rasala.jpg" },
  { name: "Dr. D. R. Chaple", image: "/committee/brochure/young-leadership/d-r-chaple.jpg" },
  { name: "Dr. Atul T. Hemke", image: "/committee/brochure/young-leadership/atul-t-hemke.jpg" },
  { name: "Dr. Sachin Dighade", image: "/committee/brochure/young-leadership/sachin-dighade.jpg" },
  { name: "Dr. Vishal Kewaldas Lokhande", image: "/committee/brochure/young-leadership/vishal-kewaldas-lokhande.jpg" },
  { name: "Dr. Upadesh B. Lade", image: "/committee/brochure/young-leadership/upadesh-b-lade.jpg" },
  { name: "Dr. Vinod M. Thakare", image: "/committee/brochure/young-leadership/vinod-m-thakare.jpg" },
  { name: "Dr. Sashi Alok", image: "/committee/brochure/young-leadership/sashi-alok.jpg" },
  { name: "Dr. Amit Verma", image: "/committee/brochure/young-leadership/amit-verma.jpg" },
  { name: "Dr. Gaurav Tiwari", image: "/committee/brochure/young-leadership/gaurav-tiwari.jpg" },
  { name: "Dr. Rakesh Punasiya", image: "/committee/brochure/young-leadership/rakesh-punasiya.jpg" },
  { name: "Dr. Aakash Marathakam", image: "/committee/brochure/young-leadership/aakash-marathakam.jpg" },
  { name: "Dr. Girendra Kumar Gautam", image: "/committee/brochure/young-leadership/girendra-kumar-gautam.jpg" },
  { name: "Dr. Gyanendra Sharma", image: "/committee/brochure/young-leadership/gyanendra-sharma.jpg" },
  { name: "Dr. Deepak Shrivastava", image: "/committee/brochure/young-leadership/deepak-shrivastava.jpg" },
  { name: "Dr. Narendra Yadav", image: "/committee/brochure/young-leadership/narendra-yadav.jpg" },
  { name: "Dr. Vikas Chandra Sharma", image: "/committee/brochure/young-leadership/vikas-chandra-sharma.jpg" },
  { name: "Dr. Nisha Sharma", image: "/committee/brochure/young-leadership/nisha-sharma.jpg" },
  { name: "Dr. Ajay Sharma", image: "/committee/brochure/young-leadership/ajay-sharma.jpg" },
  { name: "Dr. Neeraj Singh", image: "/committee/brochure/young-leadership/neeraj-singh.jpg" },
  { name: "Dr. S. S. Pandey", image: "/committee/brochure/young-leadership/s-s-pandey.jpg" },
  { name: "Dr. Sameer Rastogi", image: "/committee/brochure/young-leadership/sameer-rastogi.jpg" },
  { name: "Dr. Naveen Gupta", image: "/committee/brochure/young-leadership/naveen-gupta.jpg" },
  { name: "Dr. Swatantra Kushwaha", image: "/committee/brochure/young-leadership/swatantra-kushwaha.jpg" },
  { name: "Dr. Syed Misbul Hasan", image: "/committee/brochure/young-leadership/syed-misbul-hasan.jpg" },
  { name: "Dr. Tarique Mahmood", image: "/committee/brochure/young-leadership/tarique-mahmood.jpg" },
  { name: "Dr. U. S. Sharma", image: "/committee/brochure/young-leadership/u-s-sharma.jpg" },
  { name: "Dr. Vishal Singh", image: "/committee/brochure/young-leadership/vishal-singh.jpg" },
  { name: "Dr. A. V. Chandewar", image: "/committee/brochure/young-leadership/a-v-chandewar.jpg" },
  { name: "Dr. Neeraj Kumar", image: "/committee/brochure/young-leadership/neeraj-kumar.jpg" },
  { name: "Dr. Abhishek Kumar Singh", image: "/committee/brochure/young-leadership/abhishek-kumar-singh.jpg" },
  { name: "Dr. Kuldeep Patel", image: "/committee/brochure/young-leadership/kuldeep-patel.jpg" },
  { name: "Dr. Ajmer Singh", image: "/committee/brochure/young-leadership/ajmer-singh.jpg" },
  { name: "Dr. Amit Bhargava", image: "/committee/brochure/young-leadership/amit-bhargava.jpg" },
  { name: "Dr. Arvind Kumar Srivastava", image: "/committee/brochure/young-leadership/arvind-kumar-srivastava.jpg" },
  { name: "Dr. Anil Jadhav", image: "/committee/brochure/young-leadership/anil-jadhav.jpg" },
  { name: "Dr. Ankit Paliwal", image: "/committee/brochure/young-leadership/ankit-paliwal.jpg" },
  { name: "Dr. Ankur Agrawal", image: "/committee/brochure/young-leadership/ankur-agrawal.jpg" },
  { name: "Dr. Arvind Kumar Srivastava", image: "/committee/brochure/young-leadership/arvind-kumar-srivastava-2.jpg" },
  { name: "Dr. Ashish Gupta", image: "/committee/brochure/young-leadership/ashish-gupta.jpg" },
  { name: "Dr. Amit Bhatia", image: "/committee/brochure/young-leadership/amit-bhatia.jpg" },
  { name: "Dr. Amit Dubey", image: "/committee/brochure/young-leadership/amit-dubey.jpg" },
  { name: "Dr. Abhishek Kumar", image: "/committee/brochure/young-leadership/abhishek-kumar.jpg" },
  { name: "Dr. Ashwini Mishra", image: "/committee/brochure/young-leadership/ashwini-mishra.jpg" },
  { name: "Dr. C. Madhavi Latha", image: "/committee/brochure/young-leadership/c-madhavi-latha.jpg" },
  { name: "Dr. Chhavi Singla", image: "/committee/brochure/young-leadership/chhavi-singla.jpg" },
  { name: "Prof. (Dr.) Md. Aftab Alam", image: "/committee/brochure/young-leadership/md-aftab-alam.jpg" },
  { name: "Dr. Ashish Jain", image: "/committee/brochure/young-leadership/ashish-jain.jpg" },
  { name: "Dr. Ashish Pandey", image: "/committee/brochure/young-leadership/ashish-pandey.jpg" },
  { name: "Dr. Bhupendra Singh Chauhan", image: "/committee/brochure/young-leadership/bhupendra-singh-chauhan.jpg" },
  { name: "Dr. Bimlesh Kumar", image: "/committee/brochure/young-leadership/bimlesh-kumar.jpg" },
  { name: "Dr. Brijesh Taksande", image: "/committee/brochure/young-leadership/brijesh-taksande.jpg" },
  { name: "Dr. Hemendra Gautam", image: "/committee/brochure/young-leadership/hemendra-gautam.jpg" },
  { name: "Dr. Baljeet Singh", image: "/committee/brochure/young-leadership/baljeet-singh.jpg" },
  { name: "Dr. Dadasaheb M. Kokare", image: "/committee/brochure/young-leadership/dadasaheb-m-kokare.jpg" },
  { name: "Dr. Ganesh Mishra", image: "/committee/brochure/young-leadership/ganesh-mishra.jpg" },
  { name: "Dr. Sourabh Jain", image: "/committee/brochure/young-leadership/sourabh-jain.jpg" },
  { name: "Dr. Arun Patidar", image: "/committee/brochure/young-leadership/arun-patidar.jpg" },
  { name: "Dr. Anupam K. Sachan", image: "/committee/brochure/young-leadership/anupam-k-sachan.jpg" },
  { name: "Dr. Kamal Singh Rathore", image: "/committee/brochure/young-leadership/kamal-singh-rathore.jpg" },
  { name: "Dr. Lavakesh Kumar Omray", image: "/committee/brochure/young-leadership/lavakesh-kumar-omray.jpg" },
  { name: "Dr. Parag Gide", image: "/committee/brochure/young-leadership/parag-gide.jpg" },
  { name: "Dr. Pushpendra Kumar", image: "/committee/brochure/young-leadership/pushpendra-kumar.jpg" },
  { name: "Dr. Manish Gupta", image: "/committee/brochure/young-leadership/manish-gupta.jpg" },
  { name: "Dr. Manoj Khardiya", image: "/committee/brochure/young-leadership/manoj-khardiya.jpg" },
  { name: "Dr. Mohini Patidar", image: "/committee/brochure/young-leadership/mohini-patidar.jpg" },
  { name: "Dr. Mona Piplani", image: "/committee/brochure/young-leadership/mona-piplani.jpg" },
  { name: "Dr. Ajay Kumar", image: "/committee/brochure/young-leadership/ajay-kumar.jpg" },
  { name: "Dr. Namita Arora", image: "/committee/brochure/young-leadership/namita-arora.jpg" },
  { name: "Dr. Neelesh Kumar Dwivedi", image: "/committee/brochure/young-leadership/neelesh-kumar-dwivedi.jpg" },
  { name: "Dr. Neeraj Vyavhare", image: "/committee/brochure/young-leadership/neeraj-vyavhare.jpg" },
  { name: "Dr. Sarita Singh", image: "/committee/brochure/young-leadership/sarita-singh.jpg" },
  { name: "Dr. Alok Nahata", image: "/committee/brochure/young-leadership/alok-nahata.jpg" },
  { name: "Dr. Pankaj Arora", image: "/committee/brochure/young-leadership/pankaj-arora.jpg" },
  { name: "Dr. Pankaj Bhateja", image: "/committee/brochure/young-leadership/pankaj-bhateja.jpg" },
  { name: "Dr. Paras Gupta", image: "/committee/brochure/young-leadership/paras-gupta.jpg" },
  { name: "Dr. Pawan Basniwal", image: "/committee/brochure/young-leadership/pawan-basniwal.jpg" },
  { name: "Dr. Dimak Chand Sahu", image: "/committee/brochure/young-leadership/dimak-chand-sahu.jpg" },
  { name: "Dr. Pranav J. Shah", image: "/committee/brochure/young-leadership/pranav-j-shah.jpg" },
  { name: "Dr. Prashant Beniwal", image: "/committee/brochure/young-leadership/prashant-beniwal.jpg" },
  { name: "Dr. Pravin Suruse", image: "/committee/brochure/young-leadership/pravin-suruse.jpg" },
  { name: "Dr. Raghvendra Bhadauriya", image: "/committee/brochure/young-leadership/raghvendra-bhadauriya.jpg" },
  { name: "Dr. Rahul Taneja", image: "/committee/brochure/young-leadership/rahul-taneja.jpg" },
  { name: "Dr. Ram Darshan Parashar", image: "/committee/brochure/young-leadership/ram-darshan-parashar.jpg" },
  { name: "Dr. Ravindra Pal Singh", image: "/committee/brochure/young-leadership/ravindra-pal-singh.jpg" },
  { name: "Dr. Reecha Madan", image: "/committee/brochure/young-leadership/reecha-madan.jpg" },
  { name: "Dr. Praveen Soni", image: "/committee/brochure/young-leadership/praveen-soni.jpg" },
  { name: "Dr. Ritu Kataria", image: "/committee/brochure/young-leadership/ritu-kataria.jpg" },
  { name: "Dr. Sailesh J. Wadher", image: "/committee/brochure/young-leadership/sailesh-j-wadher.jpg" },
  { name: "Dr. Saras Kumar Jain", image: "/committee/brochure/young-leadership/saras-kumar-jain.jpg" },
  { name: "Dr. Seema Sharma", image: "/committee/brochure/young-leadership/seema-sharma.jpg" },
  { name: "Dr. Shivani Patidar", image: "/committee/brochure/young-leadership/shivani-patidar.jpg" },
  { name: "Dr. Renu", image: "/committee/brochure/young-leadership/renu.jpg" },
  { name: "Dr. Ruchi Tiwari", image: "/committee/brochure/young-leadership/ruchi-tiwari.jpg" },
  { name: "Dr. Shiv Garg", image: "/committee/brochure/young-leadership/shiv-garg.jpg" },
  { name: "Dr. Shailendra Bhatt", image: "/committee/brochure/young-leadership/shailendra-bhatt.jpg" },
  { name: "Dr. Shirish P. Jain", image: "/committee/brochure/young-leadership/shirish-p-jain.jpg" },
  { name: "Dr. Sujit Pillai", image: "/committee/brochure/young-leadership/sujit-pillai.jpg" },
  { name: "Dr. Suman Rohila", image: "/committee/brochure/young-leadership/suman-rohila.jpg" },
  { name: "Dr. Rajesh Nagar", image: "/committee/brochure/young-leadership/rajesh-nagar.jpg" },
  { name: "Dr. Sunil Yadav", image: "/committee/brochure/young-leadership/sunil-yadav.jpg" },
  { name: "Dr. Sunita Patidar", image: "/committee/brochure/young-leadership/sunita-patidar.jpg" },
  { name: "Dr. Suresh Chaudhary", image: "/committee/brochure/young-leadership/suresh-chaudhary.jpg" },
  { name: "Dr. Suresh Kumar Beniwal", image: "/committee/brochure/young-leadership/suresh-kumar-beniwal.jpg" },
  { name: "Dr. Suresh Thareja", image: "/committee/brochure/young-leadership/suresh-thareja.jpg" },
  { name: "Dr. Vivekkumar Redasani", image: "/committee/brochure/young-leadership/vivekkumar-redasani.jpg" },
  { name: "Dr. Umesh Gupta", image: "/committee/brochure/young-leadership/umesh-gupta.jpg" },
  { name: "Dr. Manish Patidar", image: "/committee/brochure/young-leadership/manish-patidar.jpg" },
  { name: "Dr. Sandip Zine", image: "/committee/brochure/young-leadership/sandip-zine.jpg" },
  { name: "Dr. Ajay Kshirsagar", image: "/committee/brochure/young-leadership/ajay-kshirsagar.jpg" },
  { name: "Manoj Phadtare", image: "/committee/brochure/young-leadership/manoj-phadtare.jpg" },
  { name: "Shilpa Deshpande", image: "/committee/brochure/young-leadership/shilpa-deshpande.jpg" },
  { name: "Dr. Y. Sridhar", image: "/committee/brochure/young-leadership/y-sridhar.jpg" },
  { name: "Sanjay Thonte", image: "/committee/brochure/young-leadership/sanjay-thonte.jpg" },
  { name: "Prashant Deshmukh", image: "/committee/brochure/young-leadership/prashant-deshmukh.jpg" },
  { name: "Vidhya Bhusari", image: "/committee/brochure/young-leadership/vidhya-bhusari.jpg" },
  { name: "Dr. Amit Kumar Verma", image: "/committee/brochure/young-leadership/amit-kumar-verma.jpg" },
  { name: "Dr. Swaroop Lahoti", image: "/committee/brochure/young-leadership/swaroop-lahoti.jpg" },
];

export const REGULATORY_PATRONS: CommitteeGroup[] = [
  {
    title: "Assistant Drug Controller",
    members: [
      { name: "Mr. Beniram Sahu", image: "/committee/brochure/regulatory-patrons/beniram-sahu.jpg" },
      { name: "Dr. Tripti Jain", image: "/committee/brochure/regulatory-patrons/tripti-jain.jpg" },
      { name: "Mr. Hiren Manu Bhai Patel", image: "/committee/brochure/regulatory-patrons/hiren-manu-bhai-patel.jpg" },
      { name: "Mrs. Meenakshi Vaishnav", image: "/committee/brochure/regulatory-patrons/meenakshi-vaishnav.jpg" },
      { name: "Mr. Mahendra Kumar Dewangan", image: "/committee/brochure/regulatory-patrons/mahendra-kumar-dewangan.jpg" },
      { name: "Mr. Sanjay Rajput", image: "/committee/brochure/regulatory-patrons/sanjay-rajput.jpg" },
      { name: "Mr. Ravindra Gendle", image: "/committee/brochure/regulatory-patrons/ravindra-gendle.jpg" },
      { name: "Mr. Pritam Ogrey", image: "/committee/brochure/regulatory-patrons/pritam-ogrey.jpg" },
      { name: "Mr. Bhishmdev Singh Kanwar", image: "/committee/brochure/regulatory-patrons/bhishmdev-singh-kanwar.jpg" },
      { name: "Mr. Rajesh Chhatri", image: "/committee/brochure/regulatory-patrons/rajesh-chhatri.jpg" },
      { name: "Mr. Kishore Kumar Thakur", image: "/committee/brochure/regulatory-patrons/kishore-kumar-thakur.jpg" },
      { name: "Mrs. Ramila Bhagat", image: "/committee/brochure/regulatory-patrons/ramila-bhagat.jpg" },
      { name: "Mr. Mahesh Kumar Nagvanshi", image: "/committee/brochure/regulatory-patrons/mahesh-kumar-nagvanshi.jpg" },
      { name: "Mr. Sanjay Singh Jhadker", image: "/committee/brochure/regulatory-patrons/sanjay-singh-jhadker.jpg" },
      { name: "Mr. Pitambar Sahu", image: "/committee/brochure/regulatory-patrons/pitambar-sahu.jpg" },
      { name: "Mrs. Mary Shruti Lakra", image: "/committee/brochure/regulatory-patrons/mary-shruti-lakra.jpg" },
    ],
  },
  {
    title: "Assistant Director",
    members: [
      { name: "Mr. Piyush Jaiswal", image: "/committee/brochure/regulatory-patrons/piyush-jaiswal.jpg" },
      { name: "Dr. Parmanand Verma", image: "/committee/brochure/regulatory-patrons/parmanand-verma.jpg" },
      { name: "Mr. Brijraj Singh", image: "/committee/brochure/regulatory-patrons/brijraj-singh.jpg" },
      { name: "Mr. Ratnesh Kumar Bargah", image: "/committee/brochure/regulatory-patrons/ratnesh-kumar-bargah.jpg" },
      { name: "Mr. Sumit Singh Parihar", image: "/committee/brochure/regulatory-patrons/sumit-singh-parihar.jpg" },
      { name: "Mr. Ram Brijesh Prajapati", image: "/committee/brochure/regulatory-patrons/ram-brijesh-prajapati.jpg" },
    ],
  },
  {
    title: "Drug Inspectors",
    members: [
      { name: "Mr. Vikas Lakra", image: "/committee/brochure/regulatory-patrons/vikas-lakra.jpg" },
      { name: "Mr. Sunil Kumar Mandavi", image: "/committee/brochure/regulatory-patrons/sunil-kumar-mandavi.jpg" },
      { name: "Mr. Devendra Kumar Dhruw", image: "/committee/brochure/regulatory-patrons/devendra-kumar-dhruw.jpg" },
      { name: "Mrs. Gayatri Patel", image: "/committee/brochure/regulatory-patrons/gayatri-patel.jpg" },
      { name: "Mrs. Jageshwari Sahu", image: "/committee/brochure/regulatory-patrons/jageshwari-sahu.jpg" },
      { name: "Mrs. Deepika Churendra", image: "/committee/brochure/regulatory-patrons/deepika-churendra.jpg" },
      { name: "Mr. Dhaniram Patel", image: "/committee/brochure/regulatory-patrons/dhaniram-patel.jpg" },
      { name: "Mrs. Kameshwari Patel", image: "/committee/brochure/regulatory-patrons/kameshwari-patel.jpg" },
      { name: "Mr. Durgesh Kumar Kaiwartya", image: "/committee/brochure/regulatory-patrons/durgesh-kumar-kaiwartya.jpg" },
      { name: "Ms. Neha Minz", image: "/committee/brochure/regulatory-patrons/neha-minz.jpg" },
      { name: "Mr. Bhuneshwar Prasad Mohle", image: "/committee/brochure/regulatory-patrons/bhuneshwar-prasad-mohle.jpg" },
      { name: "Mr. Lukesh Sahu", image: "/committee/brochure/regulatory-patrons/lukesh-sahu.jpg" },
      { name: "Mr. Sunil Kumar Kharanshu", image: "/committee/brochure/regulatory-patrons/sunil-kumar-kharanshu.jpg" },
      { name: "Mr. Dharamveer Singh Dhruw", image: "/committee/brochure/regulatory-patrons/dharamveer-singh-dhruw.jpg" },
      { name: "Mrs. Priyanka Diwan", image: "/committee/brochure/regulatory-patrons/priyanka-diwan.jpg" },
      { name: "Mr. Neeraj Sahu", image: "/committee/brochure/regulatory-patrons/neeraj-sahu.jpg" },
      { name: "Mr. Ashutosh Kumar Gupta", image: "/committee/brochure/regulatory-patrons/ashutosh-kumar-gupta.jpg" },
      { name: "Mr. Girijashankar", image: "/committee/brochure/regulatory-patrons/girijashankar.jpg" },
      { name: "Mrs. Lakshmi Kaushik", image: "/committee/brochure/regulatory-patrons/lakshmi-kaushik.jpg" },
      { name: "Mr. Kaushal Sahu", image: "/committee/brochure/regulatory-patrons/kaushal-sahu.jpg" },
    ],
  },
];

export const WOMEN_FORUM: CommitteeMember[] = [
  { name: "Dr. Vandana B. Patravale", role: "National Convenor, APTI-WF", image: "/committee/brochure/women-forum/vandana-b-patravale.jpg" },
  { name: "Dr. Pallaavi Ahirrao", role: "National Co-convener, APTI-WF", image: "/committee/brochure/women-forum/pallaavi-ahirrao.jpg" },
  { name: "Dr. Rashmi Trivedi", role: "National Co-convener, APTI-WF", image: "/committee/brochure/women-forum/rashmi-trivedi.jpg" },
  { name: "Dr. Lopamudra Adhikari", role: "Coordinator (East)", image: "/committee/brochure/women-forum/lopamudra-adhikari.jpg" },
  { name: "Dr. Anuradha Mujumdar", role: "Coordinator (West)", image: "/committee/brochure/women-forum/anuradha-mujumdar.jpg" },
  { name: "Dr. Vandana Soni", role: "Coordinator (Central)", image: "/committee/brochure/women-forum/vandana-soni.jpg" },
  { name: "Prof. Vanaja Kenchappa", role: "Coordinator (South)", image: "/committee/brochure/women-forum/vanaja-kenchappa.jpg" },
  { name: "Dr. Pooja Chawla", role: "Coordinator (North)", image: "/committee/brochure/women-forum/pooja-chawla.jpg" },
  { name: "Prof. Bharti Ahirwar", role: "Member", image: "/committee/brochure/women-forum/bharti-ahirwar.jpg" },
  { name: "Dr. Ankur Gera", role: "Member", image: "/committee/brochure/women-forum/ankur-gera.jpg" },
  { name: "Dr. Shilpriya Walde", role: "Member", image: "/committee/brochure/women-forum/shilpriya-walde.jpg" },
  { name: "Dr. Yogita Bansal", role: "Member", image: "/committee/brochure/women-forum/yogita-bansal.jpg" },
  { name: "Dr. Richa Dayaramani", role: "Member", image: "/committee/brochure/women-forum/richa-dayaramani.jpg" },
  { name: "Dr. Sangeeta Asija", role: "Member", image: "/committee/brochure/women-forum/sangeeta-asija.jpg" },
  { name: "Ms. Rakhi Khabiya", role: "Member", image: "/committee/brochure/women-forum/rakhi-khabiya.jpg" },
];

export const LOC: CommitteeGroup[] = [
  {
    title: "Chairman, LOC",
    members: [
      { name: "Prof. Deependra Singh", role: "Chairman, LOC", designation: "Professor", institution: "University Institute of Pharmacy, Pt. Ravishankar Shukla University, Raipur", image: "/committee/brochure/loc/deependra-singh.jpg" },
    ],
  },
  {
    title: "Co-Chairman, LOC",
    members: [
      { name: "Dr. Nirmal Dongre", role: "Co-Chairman, LOC", image: "/committee/brochure/loc/nirmal-dongre.jpg" },
      { name: "Prof. Shekhar Verma", role: "Co-Chairman, LOC", image: "/committee/brochure/loc/shekhar-verma.jpg" },
      { name: "Prof. Ajazuddin", role: "Co-Chairman, LOC", image: "/committee/brochure/loc/ajazuddin.jpg" },
      { name: "Prof. Shailesh Jain", role: "Co-Chairman, LOC", image: "/committee/brochure/loc/shailesh-jain.jpg" },
    ],
  },
  {
    title: "Organizing Secretary",
    members: [
      { name: "Prof. Amber Vyas", role: "Organizing Secretary", designation: "Professor", institution: "University Institute of Pharmacy, Pt. Ravishankar Shukla University, Raipur", image: "/committee/brochure/loc/amber-vyas.jpg" },
    ],
  },
  {
    title: "Joint Organizing Secretaries",
    members: [
      { name: "Prof. Shiv Shankar Shukla", role: "Joint Organizing Secretary", image: "/committee/brochure/loc/shiv-shankar-shukla.jpg" },
      { name: "Dr. Rakesh Patel", role: "Joint Organizing Secretary", image: "/committee/brochure/loc/rakesh-patel.jpg" },
      { name: "Dr. Gajanand Engla", role: "Joint Organizing Secretary", image: "/committee/brochure/loc/gajanand-engla.jpg" },
    ],
  },
  {
    title: "Associate Secretaries",
    members: [
      { name: "Dr. Satyendra Shrivastav", role: "Associate Secretary", image: "/committee/brochure/loc/satyendra-shrivastav.jpg" },
      { name: "Dr. Ravindra Pandey", role: "Associate Secretary", image: "/committee/brochure/loc/ravindra-pandey.jpg" },
      { name: "Dr. Dheeraj Ahirwar", role: "Associate Secretary", image: "/committee/brochure/loc/dheeraj-ahirwar.jpg" },
      { name: "Dr. Sudhir Bharadwaj", role: "Associate Secretary", image: "/committee/brochure/loc/sudhir-bharadwaj.jpg" },
      { name: "Dr. Mukesh Sharma", role: "Associate Secretary", image: "/committee/brochure/loc/mukesh-sharma.jpg" },
      { name: "Dr. Alok Pal Jain", role: "Associate Secretary", image: "/committee/brochure/loc/alok-pal-jain.jpg" },
    ],
  },
  {
    title: "Treasurer",
    members: [
      { name: "Prof. Vishal Jain", role: "Treasurer", image: "/committee/brochure/loc/vishal-jain.jpg" },
    ],
  },
];

export const SCIENTIFIC_COMMITTEE: CommitteeMember[] = [
  { name: "Dr. Manju Singh", role: "Chairman", image: "/committee/brochure/scientific-committee/manju-singh.jpg" },
  { name: "Dr. Madhulika Pradhan", role: "Co-Chairman", image: "/committee/brochure/scientific-committee/madhulika-pradhan.jpg" },
  { name: "Dr. Beena Gidwani", role: "Co-Chairman", image: "/committee/brochure/scientific-committee/beena-gidwani.jpg" },
  { name: "Dr. Sanjay Kumar Gupta", role: "Member", image: "/committee/brochure/scientific-committee/sanjay-kumar-gupta.jpg" },
  { name: "Dr. Sunita Minz", role: "Member", image: "/committee/brochure/scientific-committee/sunita-minz.jpg" },
  { name: "Ms. Rajni Yadav", role: "Member", image: "/committee/brochure/scientific-committee/rajni-yadav.jpg" },
  { name: "Mr. Kushagra Nagori", role: "Member", image: "/committee/brochure/scientific-committee/kushagra-nagori.jpg" },
  { name: "Dr. Monika Bhairam", role: "Member", image: "/committee/brochure/scientific-committee/monika-bhairam.jpg" },
  { name: "Dr. Disha Kesharwani", role: "Member", image: "/committee/brochure/scientific-committee/disha-kesharwani.jpg" },
  { name: "Ms. Sandhya Mishra", role: "Member", image: "/committee/brochure/scientific-committee/sandhya-mishra.jpg" },
  { name: "Ms. Astha Verma", role: "Member", image: "/committee/brochure/scientific-committee/astha-verma.jpg" },
];

export const REGISTRATION_COMMITTEE: CommitteeMember[] = [
  { name: "Dr. Amit Roy", role: "Chairman", image: "/committee/brochure/registration-committee/amit-roy.jpg" },
  { name: "Dr. Mehta Parulben", role: "Co-Chairman", image: "/committee/brochure/registration-committee/mehta-parulben.jpg" },
  { name: "Dr. Krishna Yadav", role: "Co-Chairman", image: "/committee/brochure/registration-committee/krishna-yadav.jpg" },
  { name: "Dr. Vikas Jain", role: "Member", image: "/committee/brochure/registration-committee/vikas-jain.jpg" },
  { name: "Dr. Sunil Kumar Dwivedi", role: "Member", image: "/committee/brochure/registration-committee/sunil-kumar-dwivedi.jpg" },
  { name: "Dr. Vishwanath Gupta", role: "Member", image: "/committee/brochure/registration-committee/vishwanath-gupta.jpg" },
];

export const TASK_COMMITTEES: CommitteeGroup[] = [
  {
    title: "Transport Committee",
    members: [
      { name: "Dr. S. P. Rao", role: "Chairman", image: "/committee/brochure/task-committees/s-p-rao.jpg" },
      { name: "Dr. Rajendra Jangde", role: "Co-Chairman", image: "/committee/brochure/task-committees/rajendra-jangde.jpg" },
      { name: "Dr. Vikas Sharma", role: "Co-Chairman", image: "/committee/brochure/task-committees/vikas-sharma.jpg" },
      { name: "Dr. Darshan Dubey", role: "Member", image: "/committee/brochure/task-committees/darshan-dubey.jpg" },
      { name: "Dr. Raghvendra Dubey", role: "Member", image: "/committee/brochure/task-committees/raghvendra-dubey.jpg" },
      { name: "Mr. Kumar Bandhu Lathiyare", role: "Member", image: "/committee/brochure/task-committees/kumar-bandhu-lathiyare.jpg" },
      { name: "Mr. Rahul Singh", role: "Member", image: "/committee/brochure/task-committees/rahul-singh.jpg" },
    ],
  },
  {
    title: "Accommodation Committee",
    members: [
      { name: "Dr. D. K. Pradhan", role: "Chairman", image: "/committee/brochure/task-committees/d-k-pradhan.jpg" },
      { name: "Dr. Vijay Singh", role: "Co-Chairman", image: "/committee/brochure/task-committees/vijay-singh.jpg" },
      { name: "Dr. Deepak Kashyap", role: "Co-Chairman", image: "/committee/brochure/task-committees/deepak-kashyap.jpg" },
      { name: "Dr. Harit Kumar Rawal", role: "Member", image: "/committee/brochure/task-committees/harit-kumar-rawal.jpg" },
      { name: "Dr. Nagendra Bhuwane", role: "Member", image: "/committee/brochure/task-committees/nagendra-bhuwane.jpg" },
      { name: "Dr. Sarang Kumar Jain", role: "Member", image: "/committee/brochure/task-committees/sarang-kumar-jain.jpg" },
      { name: "Dr. Gaurav Verma", role: "Member", image: "/committee/brochure/task-committees/gaurav-verma.jpg" },
    ],
  },
  {
    title: "Stage Committee",
    members: [
      { name: "Dr. Shruti Rathore", role: "Chairman", image: "/committee/brochure/task-committees/shruti-rathore.jpg" },
      { name: "Dr. Veena Devi", role: "Co-Chairman", image: "/committee/brochure/task-committees/veena-devi.jpg" },
      { name: "Dr. Sapna Malviya", role: "Co-Chairman", image: "/committee/brochure/task-committees/sapna-malviya.jpg" },
      { name: "Ms. Priya Namdeo", role: "Member", image: "/committee/brochure/task-committees/priya-namdeo.jpg" },
      { name: "Dr. Garvita Joshi", role: "Member", image: "/committee/brochure/task-committees/garvita-joshi.jpg" },
      { name: "Dr. Anu Hardenia", role: "Member", image: "/committee/brochure/task-committees/anu-hardenia.jpg" },
      { name: "Dr. Pragya Baghel", role: "Member", image: "/committee/brochure/task-committees/pragya-baghel.jpg" },
    ],
  },
  {
    title: "Venue Management Committee",
    members: [
      { name: "Dr. Rajesh Neema", role: "Chairman", image: "/committee/brochure/task-committees/rajesh-neema.jpg" },
      { name: "Dr. Adeep Khujur", role: "Co-Chairman", image: "/committee/brochure/task-committees/adeep-khujur.jpg" },
      { name: "Dr. Sudha Vengurlekar", role: "Co-Chairman", image: "/committee/brochure/task-committees/sudha-vengurlekar.jpg" },
      { name: "Mr. Arun Parihar", role: "Member", image: "/committee/brochure/task-committees/arun-parihar.jpg" },
      { name: "Dr. Vineet Singh", role: "Member", image: "/committee/brochure/task-committees/vineet-singh.jpg" },
      { name: "Dr. Rishi Paliwal", role: "Member", image: "/committee/brochure/task-committees/rishi-paliwal.jpg" },
      { name: "Dr. Shilpi Prasad", role: "Member", image: "/committee/brochure/task-committees/shilpi-prasad.jpg" },
    ],
  },
  {
    title: "Social Media Committee",
    members: [
      { name: "Dr. Surendra Saraf", role: "Chairman", image: "/committee/brochure/task-committees/surendra-saraf.jpg" },
      { name: "Dr. Ashish Majumdar", role: "Co-Chairman", image: "/committee/brochure/task-committees/ashish-majumdar.jpg" },
      { name: "Dr. Neetesh Kumar Jain", role: "Co-Chairman", image: "/committee/brochure/task-committees/neetesh-kumar-jain.jpg" },
      { name: "Dr. Subodh Dubey", role: "Member", image: "/committee/brochure/task-committees/subodh-dubey.jpg" },
      { name: "Dr. Devendra Singh Lodhi", role: "Member", image: "/committee/brochure/task-committees/devendra-singh-lodhi.jpg" },
      { name: "Dr. Suman Gehlot", role: "Member", image: "/committee/brochure/task-committees/suman-gehlot.jpg" },
      { name: "Dr. Pradeep Golani", role: "Member", image: "/committee/brochure/task-committees/pradeep-golani.jpg" },
    ],
  },
  {
    title: "Hospitality Committee",
    members: [
      { name: "Dr. Madhuri Baghel", role: "Chairman", image: "/committee/brochure/task-committees/madhuri-baghel.jpg" },
      { name: "Dr. Rakesh Tirkey", role: "Co-Chairman", image: "/committee/brochure/task-committees/rakesh-tirkey.jpg" },
      { name: "Dr. Vaibhav Tiwari", role: "Co-Chairman", image: "/committee/brochure/task-committees/vaibhav-tiwari.jpg" },
      { name: "Mr. Dhanush Ram Turkane", role: "Member", image: "/committee/brochure/task-committees/dhanush-ram-turkane.jpg" },
      { name: "Dr. Priya Jain", role: "Member", image: "/committee/brochure/task-committees/priya-jain.jpg" },
      { name: "Dr. Sumeet Dwivedi", role: "Member", image: "/committee/brochure/task-committees/sumeet-dwivedi.jpg" },
      { name: "Mrs. Stuti Mishra", role: "Member", image: "/committee/brochure/task-committees/stuti-mishra.jpg" },
    ],
  },
  {
    title: "Food & Catering Committee",
    members: [
      { name: "Dr. Aditya Pandey", role: "Chairman", image: "/committee/brochure/task-committees/aditya-pandey.jpg" },
      { name: "Dr. Ritesh Jain", role: "Co-Chairman", image: "/committee/brochure/task-committees/ritesh-jain.jpg" },
      { name: "Dr. Rupesh Soni", role: "Co-Chairman", image: "/committee/brochure/task-committees/rupesh-soni.jpg" },
      { name: "Dr. Atul Tripathi", role: "Member", image: "/committee/brochure/task-committees/atul-tripathi.jpg" },
      { name: "Dr. Shantilal Singune", role: "Member", image: "/committee/brochure/task-committees/shantilal-singune.jpg" },
      { name: "Dr. Ajay Raghuvanshi", role: "Member", image: "/committee/brochure/task-committees/ajay-raghuvanshi.jpg" },
      { name: "Dr. Parag Jain", role: "Member", image: "/committee/brochure/task-committees/parag-jain.jpg" },
    ],
  },
  {
    title: "Inaugural and Valedictory Committee",
    members: [
      { name: "Dr. Rohitas Deshmukh", role: "Chairman", image: "/committee/brochure/task-committees/rohitas-deshmukh.jpg" },
      { name: "Dr. Pratap Singh Jadon", role: "Co-Chairman", image: "/committee/brochure/task-committees/pratap-singh-jadon.jpg" },
      { name: "Dr. Gyanesh", role: "Co-Chairman", image: "/committee/brochure/task-committees/gyanesh.jpg" },
      { name: "Dr. Narendra Pratap Singh Sengar", role: "Member", image: "/committee/brochure/task-committees/narendra-pratap-singh-sengar.jpg" },
      { name: "Dr. Janki Prasad Rai", role: "Member", image: "/committee/brochure/task-committees/janki-prasad-rai.jpg" },
      { name: "Dr. Astha Verma", role: "Member", image: "/committee/brochure/task-committees/astha-verma.jpg" },
      { name: "Dr. Aakash Singh Panwar", role: "Member", image: "/committee/brochure/task-committees/aakash-singh-panwar.jpg" },
    ],
  },
  {
    title: "Entertainment Committee",
    members: [
      { name: "Dr. Harish Sharma", role: "Chairman", image: "/committee/brochure/task-committees/harish-sharma.jpg" },
      { name: "Dr. Yogesh Pawanikar", role: "Co-Chairman", image: "/committee/brochure/task-committees/yogesh-pawanikar.jpg" },
      { name: "Dr. Virendra Kumar Sharma", role: "Co-Chairman", image: "/committee/brochure/task-committees/virendra-kumar-sharma.jpg" },
      { name: "Dr. Shashikant Chandrakar", role: "Member", image: "/committee/brochure/task-committees/shashikant-chandrakar.jpg" },
      { name: "Dr. Koushlesh Kumar Mishra", role: "Member", image: "/committee/brochure/task-committees/koushlesh-kumar-mishra.jpg" },
      { name: "Dr. Pratyush Jain", role: "Member", image: "/committee/brochure/task-committees/pratyush-jain.jpg" },
      { name: "Dr. Kushagra Nagori", role: "Member", image: "/committee/brochure/task-committees/kushagra-nagori.jpg" },
    ],
  },
  {
    title: "Finance Committee",
    members: [
      { name: "Dr. Trilochan Sathpathy", role: "Chairman", image: "/committee/brochure/task-committees/trilochan-sathpathy.jpg" },
      { name: "Dr. Dinesh Mishara", role: "Co-Chairman", image: "/committee/brochure/task-committees/dinesh-mishara.jpg" },
      { name: "Dr. Anand Kumar", role: "Co-Chairman", image: "/committee/brochure/task-committees/anand-kumar.jpg" },
      { name: "Dr. Ashish Pandey", role: "Member", image: "/committee/brochure/task-committees/ashish-pandey.jpg" },
      { name: "Dr. Shobhit Shrivastava", role: "Member", image: "/committee/brochure/task-committees/shobhit-shrivastava.jpg" },
      { name: "Dr. Rita Mourya", role: "Member", image: "/committee/brochure/task-committees/rita-mourya.jpg" },
      { name: "Dr. Dishant Gupta", role: "Member", image: "/committee/brochure/task-committees/dishant-gupta.jpg" },
    ],
  },
  {
    title: "Sponsorship Committee",
    members: [
      { name: "Dr. Shailesh Jain", role: "Chairman", image: "/committee/brochure/task-committees/shailesh-jain.jpg" },
      { name: "Dr. Mukesh Chandra Sharma", role: "Co-Chairman", image: "/committee/brochure/task-committees/mukesh-chandra-sharma.jpg" },
      { name: "Dr. Homesh Yadav", role: "Co-Chairman", image: "/committee/brochure/task-committees/homesh-yadav.jpg" },
      { name: "Dr. Hemant Swami", role: "Member", image: "/committee/brochure/task-committees/hemant-swami.jpg" },
      { name: "Dr. Pravin Kumar Sharma", role: "Member", image: "/committee/brochure/task-committees/pravin-kumar-sharma.jpg" },
      { name: "Dr. Prakash Kumar Soni", role: "Member", image: "/committee/brochure/task-committees/prakash-kumar-soni.jpg" },
      { name: "Dr. Monika Bhairam", role: "Member", image: "/committee/brochure/task-committees/monika-bhairam.jpg" },
    ],
  },
  {
    title: "Exhibition Committee",
    members: [
      { name: "Dr. Aditya Trivedi", role: "Chairman", image: "/committee/brochure/task-committees/aditya-trivedi.jpg" },
      { name: "Dr. Tikeshwar Kumar", role: "Co-Chairman", image: "/committee/brochure/task-committees/tikeshwar-kumar.jpg" },
      { name: "Dr. Ram Darshan Parashar", role: "Co-Chairman", image: "/committee/brochure/task-committees/ram-darshan-parashar.jpg" },
      { name: "Dr. Sandeep Tiwari", role: "Member", image: "/committee/brochure/task-committees/sandeep-tiwari.jpg" },
      { name: "Dr. Kunjbihari Sulakhiya", role: "Member", image: "/committee/brochure/task-committees/kunjbihari-sulakhiya.jpg" },
      { name: "Dr. L. N. Patidar", role: "Member", image: "/committee/brochure/task-committees/l-n-patidar.jpg" },
      { name: "Dr. Dharmendra Solanki", role: "Member", image: "/committee/brochure/task-committees/dharmendra-solanki.jpg" },
    ],
  },
  {
    title: "Souvenir Committee",
    members: [
      { name: "Prof. S. J. Daharwal", role: "Chairman", image: "/committee/brochure/task-committees/s-j-daharwal.jpg" },
      { name: "Dr. Ravishankar Pandey", role: "Co-Chairman", image: "/committee/brochure/task-committees/ravishankar-pandey.jpg" },
      { name: "Dr. Rupesh Kumar Pandey", role: "Co-Chairman", image: "/committee/brochure/task-committees/rupesh-kumar-pandey.jpg" },
      { name: "Dr. Arpan Tripathi", role: "Member", image: "/committee/brochure/task-committees/arpan-tripathi.jpg" },
      { name: "Dr. Pradeep Pal", role: "Member", image: "/committee/brochure/task-committees/pradeep-pal.jpg" },
      { name: "Dr. Paras Gupta", role: "Member", image: "/committee/brochure/task-committees/paras-gupta.jpg" },
      { name: "Dr. Shailesh Kumar Gupta", role: "Member", image: "/committee/brochure/task-committees/shailesh-kumar-gupta.jpg" },
    ],
  },
  {
    title: "Press & Publicity Committee",
    members: [
      { name: "Dr. Rahul Yadav", role: "Chairman", image: "/committee/brochure/task-committees/rahul-yadav.jpg" },
      { name: "Dr. Anil Sahu", role: "Co-Chairman", image: "/committee/brochure/task-committees/anil-sahu.jpg" },
      { name: "Dr. Pradeep Kumar Tiwari", role: "Co-Chairman", image: "/committee/brochure/task-committees/pradeep-kumar-tiwari.jpg" },
      { name: "Dr. Bibekananda Meher", role: "Member", image: "/committee/brochure/task-committees/bibekananda-meher.jpg" },
      { name: "Dr. Abhishek Kumar Jain", role: "Member", image: "/committee/brochure/task-committees/abhishek-kumar-jain.jpg" },
      { name: "Dr. Urvesh Singh Narwaria", role: "Member", image: "/committee/brochure/task-committees/urvesh-singh-narwaria.jpg" },
      { name: "Dr. Gunjan Kalyani", role: "Member", image: "/committee/brochure/task-committees/gunjan-kalyani.jpg" },
    ],
  },
  {
    title: "Website Management Committee",
    members: [
      { name: "Dr. Deepak Das", role: "Chairman", image: "/committee/brochure/task-committees/deepak-das.jpg" },
      { name: "Dr. Rajnikant Panik", role: "Co-Chairman", image: "/committee/brochure/task-committees/rajnikant-panik.jpg" },
      { name: "Dr. Achal Mishra", role: "Co-Chairman", image: "/committee/brochure/task-committees/achal-mishra.jpg" },
      { name: "Dr. Deependra Soni", role: "Member", image: "/committee/brochure/task-committees/deependra-soni.jpg" },
      { name: "Dr. Umakant Sahu", role: "Member", image: "/committee/brochure/task-committees/umakant-sahu.jpg" },
      { name: "Lukeshwari Verma", role: "Member", image: "/committee/brochure/task-committees/lukeshwari-verma.jpg" },
      { name: "Dr. Sweta Koka", role: "Member", image: "/committee/brochure/task-committees/sweta-koka.jpg" },
    ],
  },
  {
    title: "Creative Committee",
    members: [
      { name: "Dr. Devendra Sahu", role: "Chairman", image: "/committee/brochure/task-committees/devendra-sahu.jpg" },
      { name: "Dr. Nilesh Malviya", role: "Co-Chairman", image: "/committee/brochure/task-committees/nilesh-malviya.jpg" },
      { name: "Mr. Rithik Shukla", role: "Co-Chairman", image: "/committee/brochure/task-committees/rithik-shukla.jpg" },
      { name: "Dr. Mohit Chaturvedi", role: "Member", image: "/committee/brochure/task-committees/mohit-chaturvedi.jpg" },
      { name: "Dr. Niharika Gokhale", role: "Member", image: "/committee/brochure/task-committees/niharika-gokhale.jpg" },
      { name: "Dr. Rishi Kumar Mishra", role: "Member", image: "/committee/brochure/task-committees/rishi-kumar-mishra.jpg" },
      { name: "Hitu Baghel", role: "Member", image: "/committee/brochure/task-committees/hitu-baghel.jpg" },
    ],
  },
  {
    title: "Oral Presentation Evaluation Committee",
    members: [
      { name: "Prof. Preeti Suresh", role: "Chairman", image: "/committee/brochure/task-committees/preeti-suresh.jpg" },
      { name: "Dr. Akhilesh Jain", role: "Co-Chairman", image: "/committee/brochure/task-committees/akhilesh-jain.jpg" },
      { name: "Dr. Rajesh Sharma", role: "Co-Chairman", image: "/committee/brochure/task-committees/rajesh-sharma.jpg" },
      { name: "Dr. Gaurav Goyanar", role: "Member", image: "/committee/brochure/task-committees/gaurav-goyanar.jpg" },
      { name: "Dr. Vibhor Jain", role: "Member", image: "/committee/brochure/task-committees/vibhor-jain.jpg" },
      { name: "Dr. Shelly Choudhry", role: "Member", image: "/committee/brochure/task-committees/shelly-choudhry.jpg" },
      { name: "Dr. Naveen Choudhary", role: "Member", image: "/committee/brochure/task-committees/naveen-choudhary.jpg" },
    ],
  },
  {
    title: "Poster Evaluation Committee",
    members: [
      { name: "Dr. Luv Kumar Soni", role: "Chairman", image: "/committee/brochure/task-committees/luv-kumar-soni.jpg" },
      { name: "Dr. Nagendra Chouhan", role: "Co-Chairman", image: "/committee/brochure/task-committees/nagendra-chouhan.jpg" },
      { name: "Dr. Saket Chandel", role: "Co-Chairman", image: "/committee/brochure/task-committees/saket-chandel.jpg" },
      { name: "Dr. Manoj Kumar", role: "Member", image: "/committee/brochure/task-committees/manoj-kumar.jpg" },
      { name: "Dr. Lubhan Singh", role: "Member", image: "/committee/brochure/task-committees/lubhan-singh.jpg" },
      { name: "Dr. Ganesh Mishra", role: "Member", image: "/committee/brochure/task-committees/ganesh-mishra.jpg" },
      { name: "Dr. Prerna Chaturvedi", role: "Member", image: "/committee/brochure/task-committees/prerna-chaturvedi.jpg" },
    ],
  },
  {
    title: "Ideathon Committee",
    members: [
      { name: "Prof. Swarnali Das", role: "Chairman", image: "/committee/brochure/task-committees/swarnali-das.jpg" },
      { name: "Dr. Yogesh Vaishnav", role: "Co-Chairman", image: "/committee/brochure/task-committees/yogesh-vaishnav.jpg" },
      { name: "Dr. Sunil Jain", role: "Co-Chairman", image: "/committee/brochure/task-committees/sunil-jain.jpg" },
      { name: "Dr. Ashutosh Gopal", role: "Member", image: "/committee/brochure/task-committees/ashutosh-gopal.jpg" },
      { name: "Dr. Alok Singh Thakur", role: "Member", image: "/committee/brochure/task-committees/alok-singh-thakur.jpg" },
      { name: "Dr. Akash Yadav", role: "Member", image: "/committee/brochure/task-committees/akash-yadav.jpg" },
      { name: "Dr. Vikas Gupta", role: "Member", image: "/committee/brochure/task-committees/vikas-gupta.jpg" },
    ],
  },
  {
    title: "Help Desk",
    members: [
      { name: "Dr. Alankar Shrivastav", role: "Chairman", image: "/committee/brochure/task-committees/alankar-shrivastav.jpg" },
      { name: "Dr. Hemant Badwaik", role: "Co-Chairman", image: "/committee/brochure/task-committees/hemant-badwaik.jpg" },
      { name: "Prof. Sushil Kumar Kashaw", role: "Co-Chairman", image: "/committee/brochure/task-committees/sushil-kumar-kashaw.jpg" },
      { name: "Dr. Rupendra Kumar Goyal", role: "Member", image: "/committee/brochure/task-committees/rupendra-kumar-goyal.jpg" },
      { name: "Dr. Sanjay Lanziyana", role: "Member", image: "/committee/brochure/task-committees/sanjay-lanziyana.jpg" },
      { name: "Dr. Suresh Paswan", role: "Member", image: "/committee/brochure/task-committees/suresh-paswan.jpg" },
      { name: "Dr. Harish Rajak", role: "Member", image: "/committee/brochure/task-committees/harish-rajak.jpg" },
    ],
  },
  {
    title: "Woman Forum",
    members: [
      { name: "Prof. Chanchal Deep Kaur", role: "Chairman", image: "/committee/brochure/task-committees/chanchal-deep-kaur.jpg" },
      { name: "Dr. Anshita Gupta", role: "Co-Chairman", image: "/committee/brochure/task-committees/anshita-gupta.jpg" },
      { name: "Dr. Rakhi Khabia", role: "Co-Chairman", image: "/committee/brochure/task-committees/rakhi-khabia.jpg" },
      { name: "Dr. Pushpa Prasad", role: "Member", image: "/committee/brochure/task-committees/pushpa-prasad.jpg" },
      { name: "Dr. Gunjan Jeswani", role: "Member", image: "/committee/brochure/task-committees/gunjan-jeswani.jpg" },
      { name: "Meenakshi Jaiswal", role: "Member", image: "/committee/brochure/task-committees/meenakshi-jaiswal.jpg" },
      { name: "Mrs. Astha Pathak", role: "Member", image: "/committee/brochure/task-committees/astha-pathak.jpg" },
    ],
  },
  {
    title: "Technical Committee",
    members: [
      { name: "Dr. Junaid Khan", role: "Chairman", image: "/committee/brochure/task-committees/junaid-khan.jpg" },
      { name: "Dr. Sandeep Sonkar", role: "Co-Chairman", image: "/committee/brochure/task-committees/sandeep-sonkar.jpg" },
      { name: "Dr. Manoj Sharma", role: "Co-Chairman", image: "/committee/brochure/task-committees/manoj-sharma.jpg" },
      { name: "Dr. Rashmi Dahima", role: "Member", image: "/committee/brochure/task-committees/rashmi-dahima.jpg" },
      { name: "Dr. Ashish Gupta", role: "Member", image: "/committee/brochure/task-committees/ashish-gupta.jpg" },
      { name: "Dr. Ruchi Khare Shrivastava", role: "Member", image: "/committee/brochure/task-committees/ruchi-khare-shrivastava.jpg" },
      { name: "Dr. Pradeep Singh Tomar", role: "Member", image: "/committee/brochure/task-committees/pradeep-singh-tomar.jpg" },
    ],
  },
  {
    title: "Prize Distribution Committee",
    members: [
      { name: "Shruti Ranjan Mishra", role: "Chairman", image: "/committee/brochure/task-committees/shruti-ranjan-mishra.jpg" },
      { name: "Dr. Amit Nayak", role: "Co-Chairman", image: "/committee/brochure/task-committees/amit-nayak.jpg" },
      { name: "Dr. Pritesh Paliwal", role: "Co-Chairman", image: "/committee/brochure/task-committees/pritesh-paliwal.jpg" },
      { name: "Dr. Vivek Pathak", role: "Member", image: "/committee/brochure/task-committees/vivek-pathak.jpg" },
      { name: "Dr. Ranjeet Harwansh", role: "Member", image: "/committee/brochure/task-committees/ranjeet-harwansh.jpg" },
      { name: "Dr. Reenu Yadav", role: "Member", image: "/committee/brochure/task-committees/reenu-yadav.jpg" },
      { name: "Dr. Sandeep Gupta", role: "Member", image: "/committee/brochure/task-committees/sandeep-gupta.jpg" },
    ],
  },
  {
    title: "Feedback Committee",
    members: [
      { name: "Dr. Vikas Jain", role: "Chairman", image: "/committee/brochure/task-committees/vikas-jain.jpg" },
      { name: "Dr. Arun K. Patel", role: "Co-Chairman", image: "/committee/brochure/task-committees/arun-k-patel.jpg" },
      { name: "Dr. Arpana Indurkhya", role: "Co-Chairman", image: "/committee/brochure/task-committees/arpana-indurkhya.jpg" },
      { name: "Durga Prasad Patel", role: "Member", image: "/committee/brochure/task-committees/durga-prasad-patel.jpg" },
      { name: "Dr. Sateesh Kumar Mishra", role: "Member", image: "/committee/brochure/task-committees/sateesh-kumar-mishra.jpg" },
      { name: "Anish Chandi", role: "Member", image: "/committee/brochure/task-committees/anish-chandi.jpg" },
      { name: "Dr. Khemkaran Ahirvar", role: "Member", image: "/committee/brochure/task-committees/khemkaran-ahirvar.jpg" },
    ],
  },
  {
    title: "Sightseeing Committee",
    members: [
      { name: "Dr. Karunakar Shukla", role: "Chairman", image: "/committee/brochure/task-committees/karunakar-shukla.jpg" },
      { name: "Dr. Vishwanath Gupta", role: "Co-Chairman", image: "/committee/brochure/task-committees/vishwanath-gupta.jpg" },
      { name: "Dr. Vivek Katare", role: "Co-Chairman", image: "/committee/brochure/task-committees/vivek-katare.jpg" },
      { name: "Dr. Mangal Singh Panwar", role: "Member", image: "/committee/brochure/task-committees/mangal-singh-panwar.jpg" },
      { name: "Dr. Abhishek Dwivedi", role: "Member", image: "/committee/brochure/task-committees/abhishek-dwivedi.jpg" },
      { name: "Dr. Nivedita Gautam", role: "Member", image: "/committee/brochure/task-committees/nivedita-gautam.jpg" },
      { name: "Dr. Sanjib Bahadur", role: "Member", image: "/committee/brochure/task-committees/sanjib-bahadur.jpg" },
      { name: "Dr. Narayan Hemnani", role: "Member", image: "/committee/brochure/task-committees/narayan-hemnani.jpg" },
      { name: "Dr. Shradha Devi Dwivedi", role: "Member", image: "/committee/brochure/task-committees/shradha-devi-dwivedi.jpg" },
      { name: "Bhavana Dowand", role: "Member", image: "/committee/brochure/task-committees/bhavana-dowand.jpg" },
      { name: "Chanchal Badhai", role: "Member", image: "/committee/brochure/task-committees/chanchal-badhai.jpg" },
      { name: "Aakanchha Singh", role: "Member", image: "/committee/brochure/task-committees/aakanchha-singh.jpg" },
      { name: "Ms. Tripti Kshatri", role: "Member", image: "/committee/brochure/task-committees/tripti-kshatri.jpg" },
      { name: "Ravi Parashar", role: "Member", image: "/committee/brochure/task-committees/ravi-parashar.jpg" },
      { name: "Alka Sahu", role: "Member", image: "/committee/brochure/task-committees/alka-sahu.jpg" },
      { name: "Sachindev Yadav", role: "Member", image: "/committee/brochure/task-committees/sachindev-yadav.jpg" },
      { name: "Neha Toppo", role: "Member", image: "/committee/brochure/task-committees/neha-toppo.jpg" },
    ],
  },
  {
    title: "V.V.I.P. Hospitality Committee",
    members: [
      { name: "Dr. Jitendra Banveer", image: "/committee/brochure/task-committees/jitendra-banveer.jpg" },
      { name: "Dr. Shivendra Kumar Dwivedi", image: "/committee/brochure/task-committees/shivendra-kumar-dwivedi.jpg" },
      { name: "Ms. Devshree Gayakwad", image: "/committee/brochure/task-committees/devshree-gayakwad.jpg" },
      { name: "Dr. Hemant Khambete", image: "/committee/brochure/task-committees/hemant-khambete.jpg" },
      { name: "Dr. Revthi Gupta", image: "/committee/brochure/task-committees/revthi-gupta.jpg" },
      { name: "Dr. Rizwan Khan", image: "/committee/brochure/task-committees/rizwan-khan.jpg" },
      { name: "Dr. Javed Khan", image: "/committee/brochure/task-committees/javed-khan.jpg" },
      { name: "Dr. Praveen Tahilani", image: "/committee/brochure/task-committees/praveen-tahilani.jpg" },
      { name: "Dr. Nilesh Jain", image: "/committee/brochure/task-committees/nilesh-jain.jpg" },
      { name: "Dr. Amit Joshi", image: "/committee/brochure/task-committees/amit-joshi.jpg" },
      { name: "Dr. Rakesh Jatav", image: "/committee/brochure/task-committees/rakesh-jatav.jpg" },
      { name: "Dr. Sukhwant Singh", image: "/committee/brochure/task-committees/sukhwant-singh.jpg" },
      { name: "Dr. Tamanna Narsinghani", image: "/committee/brochure/task-committees/tamanna-narsinghani.jpg" },
      { name: "Dr. Neelam Khan", image: "/committee/brochure/task-committees/neelam-khan.jpg" },
    ],
  },
];
